Description of test_full_KN2
Home > tt2 > tests > test_full_KN2.m
test_full_KN2
PURPOSE
The test script for the Crank-Nicolson scheme with global time stepping
SYNOPSIS
This is a script file.
DESCRIPTION
The test script for the Crank-Nicolson scheme with global time stepping
CROSS-REFERENCE INFORMATION
This function calls:
diag Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
kron Kronecker product of two QTT_Tuckers
norm Frobenius norm of the QTT-Tucker
round Approximate QTT-Tucker with another one with specified accuracy
core Converts TT-matrix to TT1 cell-array format
diag Extract the diagonal of the TT-matrix
kron Kronecker product of two TT-matrices
mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
norm Matrix norm of the TT-matrix
round Approximate TT-matrix with another one with specified accuracy
size Mode sizes of the TT-matrix
tt_matrix TT_matrix class constructor
core Converts TT-tensor TT1 to old-cell array format.
diag Constructs diagonal TT-matrix from TT-tensor
kron Kronecker product of two TT-tensors
norm Frobenius norm of the TT-tensor
round Approximate TT-tensor with another one with specified accuracy
size Mode sizes of the TT-tensor
tt_tensor TT-tensor constructor
tt_eye Identity matrix in the TT-format
tt_ones Tensor of all ones
tt_qltrtoepl returns the multilevel lower-triangular Toeplitz matrix tt generated by the multi-dimensional input vector x
tt_reshape Reshape of the TT-tensor
tt_shf Upper shift matrix in the QTT-format
tt_zeros Tensor of all zeros
tt_qlaplace_dd returns a rank-3,4...4 QTT decomposition of
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
This function is called by:
SOURCE CODE
%The test script for the Crank-Nicolson scheme with global time stepping
times_glob = zeros(9,6);
appr_glob = zeros(9,6);
% for d0t=6:14
% for d0x=6:11
d0t = 12; % quantics dims for t
d0x = 10; % quantics dims for x
dpx = 2; % phys. dims for x
a = 0;
b = 1;
h = (b-a)/(2^d0x+1);
tol = 1e-6;
eps = 1e-8;
% tranges = [0, 0.01, 0.05, 0.1, 0.2, 0.5, 1, 2, 4];
tranges = [0,0.5];
Ax = tt_matrix(tt_qlaplace_dd(d0x*ones(1,dpx)));
Ax = Ax/(h^2);
Ix = tt_matrix(tt_eye(2, dpx*d0x));
x = (a+h:h:b-h)';
z = (0:h:(b-a-2*h))';
z = exp(-z.^2/(4*tranges(end)));
z = tt_reshape(tt_tensor(z), 2*ones(1,d0x), eps);
C1l = tt_matrix(tt_qltrtoepl(core(z)));
C1d = diag(diag(C1l));
C1 = C1l+ C1l' - C1d;
C1 = round(C1, eps)*h;
% C1 = toeplitz(z)*h;
% C1 = tt_matrix(full_to_nd(C1, eps));
C = [];
for i=1:dpx
    C = kron(C,C1);
end;
u00 = tt_reshape(tt_tensor(sin(pi*x)), 2*ones(1,d0x), eps);
% u00 = tt_reshape(tt_tensor(exp(-abs(x)*sqrt(0.5)/0.5)), 2*ones(1,d0x), eps);
% u00 = kron(u00,u00);
% u_ex2 = kron(exp(-x.^2*0.5/(0.25+2*tranges(end))), exp(-x.^2*0.5/(0.25+2*tranges(end))))*((4*pi*tranges(end))^(-dpx/2));
x = tt_tensor(x);
x = tt_reshape(x, 2*ones(d0x, 1), eps);
e1 = tt_tensor(tt_ones(2, d0x));
% u0 = zeros(2^d0x,2^d0x);
% u0(2:2^d0x-1, 2:2^d0x-1)=1;
% u00 = tt_reshape(tt_tensor(u00), 2*ones(1,dpx*d0x), eps);
% u_ex2 = tt_reshape(tt_tensor(u_ex2), 2*ones(1,dpx*d0x), eps);
% u0 = tt_tensor(tt_ones(d0x*dpx,2));
% u00 = kron((x-a*e1).*(b*e1-x), e1).*kron(e1, (x-a*e1).*(b*e1-x));
% u00 = ((x-a*e1).*(b*e1-x)/(a*b)).*u00;
% for i=2:gamma
%     u00 = u00.*(x-a*e1).*(b*e1-x)/(a*b);
    u00 = round(u00, eps);
% end;
u00 = kron(u00,u00);
% u_ex = round(C*u00, eps)*((4*pi*tranges(end))^(-dpx/2));
u_ex = u00*exp(-2*pi^2*tranges(end));
% u0 = round(u0, eps);
% keyboard;
spacial_rhs = tt_zeros(2,d0x*dpx);
u0 = u00;
% Now letz init the combined timestep procedure
ttimes = zeros(1, max(size(tranges))-1);
resids = zeros(1, max(size(tranges))-1);
for out_t=1:max(size(tranges))-1
    tau = (tranges(out_t+1)-tranges(out_t))/(2^d0t);
    St = tt_shf(d0t); St = tt_matrix(St); St=St'; % lower shift matrix for gradient
    It = tt_matrix(tt_eye(2,d0t));
    Grad_t = (It-St)/tau; % for gradient
    Grad_t = round(Grad_t, eps);
    KN_term = (It+St)*0.5; % Krank-Nikolson term
    KN_term = round(KN_term, eps);
    e1t = cell(d0t,1);
    for i=1:d0t
        e1t{i}=[1;0];
    end;
    e1t = tt_tensor(e1t); % first identity vector for t - we need to put u0 into rhs
    eet = tt_tensor(tt_ones(2,d0t));
%     e2t = round(e2t, 1e-12);
    % global matrix
    M = kron(Ix, Grad_t) + kron(Ax, KN_term);
    M = round(M, eps);
    % f1 = sin(pi*(1:1:2^d0x)'/(1+2^d0x));
    % u0 = full_to_qtt(f1, 1e-12);
    % u0 = tt_tensor(u0);
    % u0 = kron(u0,u0);
    % u0 = tt_tensor(tt_ones(d0x*dpx, 2));
    U = kron(u0, eet);
    tic;
    u0_rhs = u0/tau - (Ax*u0)*0.5; % stuff u0 to rhs of KN scheme
    u0_rhs = round(u0_rhs, eps);
    rhs = kron(u0_rhs, e1t) + kron(spacial_rhs, eet);
    rhs = round(rhs, eps);
    % norm_rhs = mvk(M',rhs,tol,20,tt_tensor(tt_random(2,rhs.d,2)),1000);
%     [U,swps] = dmrg_solve2(M, rhs, U, tol, [], [], 100, []);
    [U,swps] = dmrg_solve2(M, rhs, tol, 'x0', U, 'nswp', 20);
    ttimes(out_t) = toc;
%     Mx = mvk(M,U,tol,20,tt_tensor(tt_random(2,rhs.d,2)),1000);
    Mx = mvk3(M,U,tol);
    %     Mx = M*x;
    resids(out_t) = norm(Mx-rhs)/norm(rhs);
    % prepare new start
    ind = num2cell([1;2]*ones(1,U.d), 1);
%     last_indices = cell(1, d0t);
    for i=1:d0t
        ind{i+dpx*d0x}=2;
    end;
    u0 = U(ind);
    u0 = tt_reshape(u0, 2*ones(1,dpx*d0x));
%     u0 = core(U);
%     u0 = tt_elem3(u0, last_indices);
%     u0 = tt_squeeze(u0);
%     u0 = tt_tensor(u0);
%     appr = norm(u0-u00*exp(-2*pi^2*tranges(out_t+1)))/norm(u00*exp(-2*pi^2*tranges(out_t+1)))
    appr = norm(u0-u_ex)/norm(u_ex)
    fprintf('Time range: [%g; %g], solve_time = %g, resid = %3.3e, swps: %d\n', tranges(out_t), tranges(out_t+1), ttimes(out_t), resids(out_t), swps);
%     keyboard;
end;
times_glob(d0t-5, d0x-5)=sum(ttimes);
appr_glob(d0t-5, d0x-5)=appr;
% end;
% end;