Description of test_dmrg_cross
Home > tt2 > tests > test_dmrg_cross.m
test_dmrg_cross
PURPOSE
Simple script to test the stabilized dmrg-cross method
SYNOPSIS
This is a script file.
DESCRIPTION
Simple script to test the stabilized dmrg-cross method
CROSS-REFERENCE INFORMATION
This function calls:
reshape Reshape of the TT-tensor
tt_tensor TT-tensor constructor
dmrg_cross DMRG-cross method for the approximation of TT-tensors
This function is called by:
SOURCE CODE
%Simple script to test the stabilized dmrg-cross method
d=10;
%fun = @(ind) (sum(ind)+1i*ind(1));
a=10;
n=2^d; h=2*a/(n-1);
x=-a:h:a;
f=exp(-10*x.^2); f=tt_tensor(reshape(f,2*ones(1,d)),1e-9);
fun = @(ind) f(ind);
%fun = @(ind) 1;
%n=2:d+1;
n=2;
%y=tt_ones(n);
%r=ones(d+1,1);
%r(2:d-1)=2:d-1;
%y=tt_rand(n,d,r);
%fun = @(ind) y(ind);
tt=dmrg_cross(d,n,fun,1e-7,'nswp',20);