Description of canm_to_qtt
Home > tt2 > exp > canm_to_qtt.m
canm_to_qtt
PURPOSE
Converts a canonical representation to QTT-format
SYNOPSIS
function [tt]=canm_to_qtt(can,rmax,eps)
DESCRIPTION
Converts a canonical representation to QTT-format
   [TT]=CANM_TO_QTT(CAN,RMAX,EPS)
   Converts canonical representation CAN (Cell array of factors)
   of a matrix
   to QTT representation with accuracy parameter EPS
   Mode sizes should be powers of 2
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
round Approximate QTT-Tucker with another one with specified accuracy
round Approximate TT-matrix with another one with specified accuracy
size Mode sizes of the TT-matrix
round Approximate TT-tensor with another one with specified accuracy
size Mode sizes of the TT-tensor
tt_add Adds two TT-tensors in TT1 format.
tt_compr2 Tensor rounding in TT1.0 format
tt_erank Effective rank of the TT-tensor: Approximate memory definition
tt_mat_to_vec Flattens TT-matrix into TT-vector in the TT1.0 format
tt_mkron Compute Kronecker product of many TT-tensors.
tt_zeros Tensor of all zeros
This function is called by:
SOURCE CODE
function [tt]=canm_to_qtt(can,rmax,eps)
%Converts a canonical representation to QTT-format
%   [TT]=CANM_TO_QTT(CAN,RMAX,EPS)
%   Converts canonical representation CAN (Cell array of factors)
%   of a matrix
%   to QTT representation with accuracy parameter EPS
%   Mode sizes should be powers of 2
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
if (size(can,1) == 1)
  can=can';
end
d1=size(can,1);
R=size(can{1},3);
d=zeros(d1,1);
for i=1:d1
  w1=size(can{i},1);
    w=log2(w1); w=round(w);
  if (2^w ~= w1 )
     fprintf('can_to_qtt error: mode %d size = %d not a power of two \n',i,w1);
     return
  end
  d(i)=w;
end
tt=tt_zeros(sum(d),4);
tt_arr=cell(d1,1);
for i=1:R
  for s=1:d1
    %tt_arr{s}=vec_to_nd(can{s}(:,i),eps,d(s));
    tt_arr{s}=tt_mat_to_vec(full_to_nd(can{s}(:,:,i),eps,d(s)));
 end
  mat=tt_mkron(tt_arr);
  tt=tt_add(tt,mat);
  if ( tt_erank(tt) > rmax )
     tt=tt_compr2(tt,eps);
  end
end
tt=tt_compr2(tt,eps);
return