Description of test_qlaplacex_dd
Home > tt2 > exp > test_qlaplacex_dd.m
test_qlaplacex_dd
PURPOSE
test code for tt_qlaplacex_dd()
SYNOPSIS
This is a script file.
DESCRIPTION
 test code for tt_qlaplacex_dd()
 September 22, 2010
 Vladimir Kazeev
 vladimir.kazeev@gmail.com
 INM RAS
 Moscow, Russia
 Look for details in the Preprint No. 75, 2010 of
 Max-Planck Institute for Mathematics in the Sciences
 Vladimir A. Kazeev and Boris N. Khoromskij
 On explicit QTT representation of Laplace operator and its inverse
 http://www.mis.mpg.de/publications/preprints/2010/prepr2010-75.html
CROSS-REFERENCE INFORMATION
This function calls:
disp Command window display of a QTT_TUCKER
full Converts a QTT-Tucker tensor the full tensor
kron Kronecker product of two QTT_Tuckers
norm Frobenius norm of the QTT-Tucker
disp Command window display of a TT-matrix
full Transform TT-matrix to a full rectangular matrix
kron Kronecker product of two TT-matrices
norm Matrix norm of the TT-matrix
size Mode sizes of the TT-matrix
disp Command window display of a TT-tensor.
full Converts TT-tensor to the full tensor
kron Kronecker product of two TT-tensors
norm Frobenius norm of the TT-tensor
size Mode sizes of the TT-tensor
tt_mat_to_vec Flattens TT-matrix into TT-vector in the TT1.0 format
tt_qlaplacex_dd returns a rank-5 QTT decomposition of
This function is called by:
SOURCE CODE
% test code for tt_qlaplacex_dd()
%
% September 22, 2010
% Vladimir Kazeev
% vladimir.kazeev@gmail.com
% INM RAS
% Moscow, Russia
%
% Look for details in the Preprint No. 75, 2010 of
% Max-Planck Institute for Mathematics in the Sciences
% Vladimir A. Kazeev and Boris N. Khoromskij
% On explicit QTT representation of Laplace operator and its inverse
% http://www.mis.mpg.de/publications/preprints/2010/prepr2010-75.html
% d is the only parameter
d=[3,4,5];
%
D=size(d,2);
tt=tt_qlaplacex_dd(d);
tt=tt_mat_to_vec(tt);
full=nd_to_full(tt);
disp('inv computation... ');
Li=cell(D,1);
for k=1 : D
    L=2*eye(2^d(k));
    for i=1 : 2^d(k)-1
        L(i,i+1)=-1;
        L(i+1,i)=-1;
    end
    Li{k}=inv(L);
end
disp('OK');
disp('kron computation... ');
Z=Li{1};
for k=2 : D
    Z=kron(Z,Li{k});
end
disp('OK');
err=norm(full-Z,'fro');
fprintf('fro err = %e\n', err);