Description of qtttucker_to_tt
Home > tt2 > misc > qtttucker_to_tt.m
qtttucker_to_tt
PURPOSE
function [tt]=qtttucker_to_tt(fc, cr)
SYNOPSIS
function [tt]=qtttucker_to_tt(fc, cr)
DESCRIPTION
 function [tt]=qtttucker_to_tt(fc, cr)
 Builds the TT tensor from the QTT-Tucker representation,
 where fc is the Tucker factors in QTT (cell array of @tt_tensor),
 cr is the Tucker core in TT.
CROSS-REFERENCE INFORMATION
This function calls:
size Mode sizes of the TT-matrix
reshape Reshape of the TT-tensor
size Mode sizes of the TT-tensor
tt_reshape Reshape of the TT-tensor
tucker_to_tt Build TT-tensor from the QTT-Tucker representation
This function is called by:
tt_tensor TT-tensor constructor
SOURCE CODE
function [tt]=qtttucker_to_tt(fc, cr)
% function [tt]=qtttucker_to_tt(fc, cr)
% Builds the TT tensor from the QTT-Tucker representation,
% where fc is the Tucker factors in QTT (cell array of @tt_tensor),
% cr is the Tucker core in TT.
d = cr.d;
for i=1:d
    fc{i} = tt_reshape(fc{i}, prod(fc{i}.n), [], 1, fc{i}.r(fc{i}.d+1));
    fc{i} = fc{i}{1};
    fc{i} = reshape(fc{i}, size(fc{i}, 2), size(fc{i}, 3));
end;
tt = tucker_to_tt(fc, cr);
end