Description of tt_Fd_mtx1
Home > tt2 > misc > tt_Fd_mtx1.m
tt_Fd_mtx1
PURPOSE
Generates finite-difference 1D matrix of \nabla(tt_a \nabla) in QTTM format.
SYNOPSIS
function [M] = tt_Fd_mtx1(tt_a, bound1, bound2, eps)
DESCRIPTION
Generates finite-difference 1D matrix of \nabla(tt_a \nabla) in QTTM format.
   [M] = TT_FD_MTX1(TT_A, BOUND1, BOUND2) Generates finite-difference
   1D matrix of \nabla(tt_a \nabla) in QTTM format, TT_A is given in the
   QTT format, bound1,2 specify boundary conditions as x=0 and x=1,
   respectively:
     0 - Dirichlet,
     1 - Neumann
   EPS is the QTT compression tolerance
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
diag Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
core Converts TT-matrix to TT1 cell-array format
diag Extract the diagonal of the TT-matrix
size Mode sizes of the TT-matrix
core Converts TT-tensor TT1 to old-cell array format.
diag Constructs diagonal TT-matrix from TT-tensor
size Mode sizes of the TT-tensor
tt_tensor TT-tensor constructor
tt_mat_compr Tensor rounding for the TT-matrix in TT1.0 format
tt_mv Matrix-by-vector product in the TT1.0 format
tt_scal Multiply tensor by a scalar in TT1.0 format
tt_shf Upper shift matrix in the QTT-format
tt_transp Transposition of the TT matrix
This function is called by:
tt_Fd_mtx Generates finite-difference diffusion matrix in QTT
SOURCE CODE
function [M] = tt_Fd_mtx1(tt_a, bound1, bound2, eps)
%Generates finite-difference 1D matrix of \nabla(tt_a \nabla) in QTTM format.
%   [M] = TT_FD_MTX1(TT_A, BOUND1, BOUND2) Generates finite-difference
%   1D matrix of \nabla(tt_a \nabla) in QTTM format, TT_A is given in the
%   QTT format, bound1,2 specify boundary conditions as x=0 and x=1,
%   respectively:
%     0 - Dirichlet,
%     1 - Neumann
%   EPS is the QTT compression tolerance
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
d = size(tt_a, 1);
M=core(diag(tt_tensor(a)));
tt_shf_a = tt_mv(tt_shf(d), tt_a);
tt_last_elem_a = tt_a;
for i=1:d
    tt_last_elem_a{i}(1,:,:)=0;
end;
M = ttm_add(M, tt_diag(tt_shf_a));
M = ttm_add(M, tt_diag(tt_last_elem_a));
M = tt_mat_compr(M, eps);
M_shf = tt_shf_diag(tt_a, 0);
M = ttm_add(M, tt_scal(M_shf, -1));
M = ttm_add(M, tt_scal(tt_transp(M_shf), -1));
M = tt_mat_compr(M, eps);
M = tt_scal(M, (2^d+1)^2);
end