Description of my_chop2
Home > tt2 > core > my_chop2.m
my_chop2
PURPOSE
Truncation by absolution precision in Frobenius norm
SYNOPSIS
function [r] = my_chop2(sv,eps)
DESCRIPTION
Truncation by absolution precision in Frobenius norm
   [R]=MY_CHOP2(SV,EPS) truncation by absolute precision in the Frobenius
   norm. Finds minimal possible R such that \sqrt(sum(SV(R:n)^2)) < EPS
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
Vectorize this supercode
CROSS-REFERENCE INFORMATION
This function calls:
sv Computes singular values of all unfoldings of a TT-tensor
This function is called by:
qtt_tucker QTT-Tucker contructor (TT-format for the core+QTT-format for the factors)
round Approximate QTT-Tucker with another one with specified accuracy
mvk DMRG fast matrix-by-vector product, Method 1 (less accurate)
mvk2 Two-sided DMRG fast matrix-by-vector product
funcrs Cross approximation of a function of a TT-tensor, Method 1
funcrs2 Cross approximation of a function of a TT-tensor, Method 2
round Approximate TT-tensor with another one with specified accuracy
tt_tensor TT-tensor constructor
move_tt_block Performs a bubble movement of a block inside a train
mvrk Computes matvec in the QTT-Tucker "rake" format
qtt_tucker_m Compute the QTT-Tucker representation of TT
tt_mvk2 Matrix-by-vector product by DMRG/Krylov method
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
tt_reshape Reshape of the TT-tensor
tt_tuck Computes Tucker factors and Tucker core of the TT-tensor
tt_wround Approximates a vector in the weighted norm using DMRG iterations
dmrg_cross DMRG-cross method for the approximation of TT-tensors
tt_rc [Y]=TT_RC(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
filters_wtt Computes the WTT transform filters for a given tensor
SOURCE CODE
function [r] = my_chop2(sv,eps)
%Truncation by absolution precision in Frobenius norm
%   [R]=MY_CHOP2(SV,EPS) truncation by absolute precision in the Frobenius
%   norm. Finds minimal possible R such that \sqrt(sum(SV(R:n)^2)) < EPS
%
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
%Vectorize this supercode
sv0=cumsum(sv(end:-1:1).^2);
ff=find(sv0<eps.^2);
if (isempty(ff))
   r=numel(sv);
else
   r=numel(sv)-ff(end);
end
return
end