Description of reort
Home > tt2 > core > reort.m
reort
PURPOSE
Golub-Kahan reorthogonalization
SYNOPSIS
function [y]=reort(u,uadd)
DESCRIPTION
Golub-Kahan reorthogonalization
   [Y]=REORT(U,UADD) Given orthonormal matrix U, orthonormalize UADD to it
   to get orthogonal basis in [U,UADD]. Faster then the QR-decomposition,
   using the Golub-Kahan method
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
size Mode sizes of the TT-matrix
qr Left and right orthogonalization of the TT-format
size Mode sizes of the TT-tensor
This function is called by:
mvk2 Two-sided DMRG fast matrix-by-vector product
funcrs Cross approximation of a function of a TT-tensor, Method 1
funcrs2 Cross approximation of a function of a TT-tensor, Method 2
mvrk Computes matvec in the QTT-Tucker "rake" format
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
tt_wround Approximates a vector in the weighted norm using DMRG iterations
dmrg_cross DMRG-cross method for the approximation of TT-tensors
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
SOURCE CODE
function [y]=reort(u,uadd)
%Golub-Kahan reorthogonalization
%   [Y]=REORT(U,UADD) Given orthonormal matrix U, orthonormalize UADD to it
%   to get orthogonal basis in [U,UADD]. Faster then the QR-decomposition,
%   using the Golub-Kahan method
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
if (size(uadd,2)==0)
    y = u;
    return;
end;
if (size(u,1) == size(u,2))
  y=u;
  return
end
if (size(u,2) + size(uadd,2) >= size(u,1))
  uadd=uadd(:,size(u,1)-size(u,2));
end
radd=size(uadd,2);
mvr=u'*uadd; unew=uadd-u*mvr;
reort_flag=true;
while (reort_flag)
    reort_flag=false;
    j=1;
%Nice vectorization!
norm_unew=sum(unew.^2,1);
norm_uadd=sum(uadd.^2,1);
reort_flag=isempty(norm_unew <= 0.25*norm_uadd);
[unew,rv_not_used]=qr(unew,0); %Here it is ok.
if (reort_flag)
  su=u'*unew;
  uadd=unew;
  unew=unew-u*su;
end
end
y=[u,unew];
return
end