Description of tt_compr2
Home > tt2 > core > tt_compr2.m
tt_compr2
PURPOSE
Tensor rounding in TT1.0 format
SYNOPSIS
function [tt] = tt_compr2(tt,eps, max_r)
DESCRIPTION
Tensor rounding in TT1.0 format
   [TT]=TT_COMPR2(TT,EPS) Reapproximates the given TT-tensor with
   prescribed accuracy EPS. Please avoid its usage: it will be removed in
   future releases. Use round() from the object-oriented version
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
diag Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
norm Frobenius norm of the QTT-Tucker
conj Complex conjugate of a TT-matrix
core Converts TT-matrix to TT1 cell-array format
diag Extract the diagonal of the TT-matrix
norm Matrix norm of the TT-matrix
size Mode sizes of the TT-matrix
conj Compute a complex conjugate of TT-tensor
core Converts TT-tensor TT1 to old-cell array format.
diag Constructs diagonal TT-matrix from TT-tensor
norm Frobenius norm of the TT-tensor
qr Left and right orthogonalization of the TT-format
reshape Reshape of the TT-tensor
size Mode sizes of the TT-tensor
ten_conv Tensor-by-matrix multiplication of three-dimensional tensor
tt_dot2 Logarithm of the scalar product of two tensor (to avoid overflow)
This function is called by:
tt_axpy Returns A*X+P*Y in the TT-format.
tt_axpy2 Returns A*X+P*Y in the TT-format (stabilized version)
tt_mat_compr Tensor rounding for the TT-matrix in TT1.0 format
canm_to_qtt Converts a canonical representation to QTT-format
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
tt_iterapp Apply TT matrix operator to TT vector and error gracefully.
SOURCE CODE
function [tt] = tt_compr2(tt,eps, max_r)
%Tensor rounding in TT1.0 format
%   [TT]=TT_COMPR2(TT,EPS) Reapproximates the given TT-tensor with
%   prescribed accuracy EPS. Please avoid its usage: it will be removed in
%   future releases. Use round() from the object-oriented version
%
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
d = size(tt,1);
%First, estimate the logarithm of the squared norm, and then --- the norm
%of each core :-)
nrm_full=tt_dot2(tt,tt);
nrm1=nrm_full/(2*d); nrm1=exp(nrm1);
exists_max_r=1;
if ((nargin<3)||(isempty(max_r)))
    exists_max_r=0;
end;
if (nrm_full < log(1e-200)) %Something really small
  n=size(tt{1},1);
  tt{1}=zeros(n,1);
  n=size(tt{d},1);
  tt{d}=ones(n,1);
  for i=2:d-1
  n=size(tt{i},1);
  tt{i}=ones(n,1,1);
  end
  return
end
%nrmf=zeros(d,1); %Place to store the norms of QR-factors
%first, we orthogonalize the tensor from right to left until the first mode
mat=tt{d};
[q,rv]=qr(mat,0); rv=rv./nrm1; q=q.*nrm1;
tt{d}=q;
for i=(d-1):-1:2
    tt{i} = ten_conv(tt{i},3,conj(rv'));
    ncur=size(tt{i},1);
    r2=size(tt{i},2);
    r3=size(tt{i},3);
    core=permute(tt{i},[1,3,2]);
    core=reshape(core,[ncur*r3,r2]);
    [tt{i},rv]=qr(core,0); rv=rv./nrm1;
    rnew=min(r2,ncur*r3);
    tt{i}=reshape(tt{i}.*nrm1,[ncur,r3,rnew]);
    tt{i}=permute(tt{i},[1,3,2]);
end
tt{1}=tt{1}*conj(rv');
%nrmf(1)=norm(tt{1},'fro');
%nrm_full=sum(log(nrmf(1:d))); nrm1=nrm_full/d; nrm1=exp(nrm1); %This would
%be the norm of each core
%Now gradually start compression from the left, using the knowledge
%of norms
mat=tt{1};
%return;
mat(abs(mat)<1e-300)=0;
[u0,s0,ru]=svd(mat,0);
%If no scaling factors were taken out,
%then everything would be simple --- nrm=norm(diag(s0)) is the norm,
%singular values are filtered at absolute accuracy eps*nrm/sqrt(d-1)
%Here the "True" s0 matrix is up to factor of product of nrm(2:d)
%so for it we can filter the singular values just at
%eps*nrmf(1)/sqrt{d-1}
%nrmf(1)=norm(diag(s0));
%nrm=norm(diag(s0));
eps1=eps*norm(diag(s0))/sqrt(d-1); %This is the absolute accuracy to filter with
%r0=my_chop2(diag(s0),eps1);
r0=numel(find(s0>eps1));
if (exists_max_r) r0 = min(r0, max_r); end;
%keyboard;
%r0=rank(mat,eps1);
u0=u0(:,1:r0);
s0=diag(s0);
s0=s0(1:r0); % -eps1*sign(s0);
ru=ru(:,1:r0)*diag(s0)./nrm1; %This should be scaled properly
%ru=ru;
tt{1}=u0.*nrm1; %Now it is properly scaled
for i=2:d-1
    %Convolve tt{i} over the second index
%     fprintf('norm_tt{%d}=%g, norm_ru = %g\n', i, norm(reshape(tt{i}, size(tt{i},1)*size(tt{i},2), size(tt{i},3)), 'fro'), norm(ru,'fro'));
    tt{i}=ten_conv(tt{i},2,conj(ru));
    ncur=size(tt{i},1);
    r2=size(tt{i},2);
    r3=size(tt{i},3);
    core=reshape(tt{i},[ncur*r2,r3]);
    %r=rank(core,eps1);
    %keyboard;
    core(abs(core)<1e-300)=0;
    [u0,s0,ru]=svd(core,0);
    nrm=norm(diag(s0));
    eps1=eps*nrm/sqrt(d-1); %Nothing more
    %keyboard;
    %r=my_chop2(diag(s0),eps1);
    r=numel(find(s0>eps1));
    if (exists_max_r) r = min(r, max_r); end;
    u0=u0(:,1:r);
    s0=(s0(1:r,1:r))./nrm1;
    ru=ru(:,1:r)*s0;
    core=u0.*nrm1;
    tt{i}=reshape(core,[ncur,r2,r]);
end
tt{d}=tt{d}*conj(ru);
return
end