Description of tt_eye
Home > tt2 > core > tt_eye.m
tt_eye
PURPOSE
Identity matrix in the TT-format
SYNOPSIS
function [e]=tt_eye(n,varargin)
DESCRIPTION
Identity matrix in the TT-format
   [E]=TT_EYE(N,D) Computes  N^D x N^d identity matrix in the TT-format
   [E]=TT_EYE(N) Computes identity matrix, row/col mode sizes are
   specified by the vector N
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
tt_matrix TT_matrix class constructor
This function is called by:
tt_exp2 Computation of the matrix exponential of a matrix in TT format
tt_minres_selfprec Computation of the approximate TT-matrix inverse using self-prec method
tt_minres_selfprec2 Computation of the approximate TT-matrix inverse using self-prec method
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
test_full_KN2 The test script for the Crank-Nicolson scheme with global time stepping
test_steps2 Crank-Nicolson scheme with local time-stepping
SOURCE CODE
function [e]=tt_eye(n,varargin)
%Identity matrix in the TT-format
%   [E]=TT_EYE(N,D) Computes  N^D x N^d identity matrix in the TT-format
%
%   [E]=TT_EYE(N) Computes identity matrix, row/col mode sizes are
%   specified by the vector N
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
if (numel(n) == 1)
  d=varargin{1};
  n=n*ones(1,d);
else
  d=numel(n);
end
e=cell(d,1);
for i=1:d
   e{i}=eye(n(i));
end
e=tt_matrix(e); %We did it
return
end