Description of tt_effrank
Home > tt2 > core > tt_effrank.m
tt_effrank
PURPOSE
Effective rank of the TT-tensor (correct memory definition)
SYNOPSIS
function [reff]=tt_effrank(tt,s)
DESCRIPTION
Effective rank of the TT-tensor (correct memory definition)
   [REFF]=TT_EFFRANK(TT,S)
 May 26, 2011
 Vladimir Kazeev
 vladimir.kazeev@gmail.com
 INM RAS
 Moscow, Russia
CROSS-REFERENCE INFORMATION
This function calls:
mem Computes the number of parameters in the TT-matrix
size Mode sizes of the TT-matrix
mem Computes memory for TT-tensor (only for cores)
size Mode sizes of the TT-tensor
tt_qsize For a QTT decomposition _tt_,
This function is called by:
SOURCE CODE
function [reff]=tt_effrank(tt,s)
%Effective rank of the TT-tensor (correct memory definition)
%   [REFF]=TT_EFFRANK(TT,S)
% May 26, 2011
% Vladimir Kazeev
% vladimir.kazeev@gmail.com
% INM RAS
% Moscow, Russia
d=size(tt,1);
sz=tt_qsize(tt,s);
n=prod(sz,2);
mem=0;
for k=1:d
    mem=mem+numel(tt{k});
end
a=sum(n(2:d-1));
b=n(1)+n(d);
reff=sqrt(mem/a+b^2/a^2/4)-b/a/2;
return
end