Description of tt_mat_compr
Home > tt2 > core > tt_mat_compr.m
tt_mat_compr
PURPOSE
Tensor rounding for the TT-matrix in TT1.0 format
SYNOPSIS
function [res]=tt_mat_compr(mat,eps, max_rank)
DESCRIPTION
Tensor rounding for the TT-matrix in TT1.0 format
   [RES]=TT_MAT_COMPR(MAT,EPS) Compress TT matrix with accuracy EPS. Avoid
   the usage, use round() function of the object-oriented design. Will be
   removed in future releases.
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
n=size(mat{1},1);
m=size(mat{1},2);
CROSS-REFERENCE INFORMATION
This function calls:
size Mode sizes of the TT-matrix
size Mode sizes of the TT-tensor
tt_compr2 Tensor rounding in TT1.0 format
tt_mat_to_vec Flattens TT-matrix into TT-vector in the TT1.0 format
tt_vec_to_mat Converts TT-vector to TT-matrix in TT1.0 format
This function is called by:
tt_minres_selfprec Computation of the approximate TT-matrix inverse using self-prec method
tt_Fd_mtx Generates finite-difference diffusion matrix in QTT
tt_Fd_mtx1 Generates finite-difference 1D matrix of \nabla(tt_a \nabla) in QTTM format.
tt_Fd_mtx2 TT-representation of the diffusion matrix
SOURCE CODE
function [res]=tt_mat_compr(mat,eps, max_rank)
%Tensor rounding for the TT-matrix in TT1.0 format
%   [RES]=TT_MAT_COMPR(MAT,EPS) Compress TT matrix with accuracy EPS. Avoid
%   the usage, use round() function of the object-oriented design. Will be
%   removed in future releases.
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
%n=size(mat{1},1);
%m=size(mat{1},2);
if (nargin<3)
    max_rank=[];
end;
d=size(mat,1);
n=zeros(d,1); m=zeros(d,1);
for i=1:d
  n(i)=size(mat{i},1); m(i)=size(mat{i},2);
end
res=tt_vec_to_mat(tt_compr2(tt_mat_to_vec(mat),eps,max_rank),n,m);
return
end