Description of tt_min_abs
Home > tt2 > core > tt_min_abs.m
tt_min_abs
PURPOSE
Computes approximation to the minimal absolute value in a TT-tensor
SYNOPSIS
function [res,ind]=tt_min_abs(tt)
DESCRIPTION
Computes approximation to the minimal absolute value in a TT-tensor
   [RES,IND]=TT_MIN_ABS(TT) Tries to compute the minimal absolute value in
   TT-tensor
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
size Mode sizes of the TT-matrix
size Mode sizes of the TT-tensor
tt_max_abs Compute the (supposedly) maximal in modulus element in a TT-tensor
tt_ones Tensor of all ones
This function is called by:
SOURCE CODE
function [res,ind]=tt_min_abs(tt)
%Computes approximation to the minimal absolute value in a TT-tensor
%   [RES,IND]=TT_MIN_ABS(TT) Tries to compute the minimal absolute value in
%   TT-tensor
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
resmax = tt_max_abs(tt);
ons = tt_ones(size(tt));
[res,ind]=tt_max_abs(tt-ons*resmax);
res = resmax - res;
end