Description of tt_qtofull
Home > tt2 > core > tt_qtofull.m
tt_qtofull
PURPOSE
Returns a tensor _full_, given in a QTT decomposition _tt_,
SYNOPSIS
function [ful]=tt_qtofull(tt,s)
DESCRIPTION
 Returns a tensor _full_, given in a QTT decomposition _tt_,
 k-th core of which is indexed by
 i^{k}_{1} ,..., i^{k}_{s},
 k=1,...,d,
 in the full-format representation.
 The output tensor _full_ is indexed by
 i^{1}_{1} ,..., i^{d}_{1} ,...,..., i^{1}_{s} ,..., i^{d}_{s},
 April 26, 2011
 Vladimir Kazeev
 vladimir.kazeev@gmail.com
 INM RAS
 Moscow, Russia
CROSS-REFERENCE INFORMATION
This function calls:
full Converts a QTT-Tucker tensor the full tensor
full Transform TT-matrix to a full rectangular matrix
size Mode sizes of the TT-matrix
full Converts TT-tensor to the full tensor
reshape Reshape of the TT-tensor
size Mode sizes of the TT-tensor
tt_tensor TT-tensor constructor
tt_qreshape Reshapes the cores of the input (Q)TT representation.
tt_qsize For a QTT decomposition _tt_,
This function is called by:
SOURCE CODE
function [ful]=tt_qtofull(tt,s)
% Returns a tensor _full_, given in a QTT decomposition _tt_,
% k-th core of which is indexed by
% i^{k}_{1} ,..., i^{k}_{s},
% k=1,...,d,
% in the full-format representation.
% The output tensor _full_ is indexed by
% i^{1}_{1} ,..., i^{d}_{1} ,...,..., i^{1}_{s} ,..., i^{d}_{s},
%
% April 26, 2011
% Vladimir Kazeev
% vladimir.kazeev@gmail.com
% INM RAS
% Moscow, Russia
%
d=size(tt,1);
sz=tt_qsize(tt,s);
tt=tt_qreshape(tt,s,prod(sz,2));
ful=full(tt_tensor(tt));
ful=reshape(ful,reshape(sz',1,numel(sz)));
prm=zeros(1,s*d);
for k=1:d
    for l=1:s
        prm(s*k+1-l)=k+(s-l)*d;
    end
end
ful=ipermute(ful,prm);
ful=reshape(ful,[prod(sz,1),1]);
return
end