Description of tt_reverse
Home > tt2 > core > tt_reverse.m
tt_reverse
PURPOSE
Returns a reversed TT representation
SYNOPSIS
function [tt2]=tt_reverse(tt,phd)
DESCRIPTION
 Returns a reversed TT representation
   [TT2]=TT_REVERSE(TT,PHD)
 January 25, 2011
 Vladimir Kazeev
 vladimir.kazeev@gmail.com
 INM RAS
 Moscow, Russia
CROSS-REFERENCE INFORMATION
This function calls:
size Mode sizes of the TT-matrix
size Mode sizes of the TT-tensor
This function is called by:
tt_qshiftstack returns a stack S of non-periodic shift matrices
tt_qshiftstack_p returns a stack P of periodic shift matrices
tt_qshiftstack_q returns a stack Q of non-periodic shift matrices
tt_qshiftstack_r returns a stack R of non-periodic shift matrices
SOURCE CODE
function [tt2]=tt_reverse(tt,phd)
% Returns a reversed TT representation
%   [TT2]=TT_REVERSE(TT,PHD)
% January 25, 2011
% Vladimir Kazeev
% vladimir.kazeev@gmail.com
% INM RAS
% Moscow, Russia
%
d=size(tt,1);
tt2=cell(d,1);
tt2{1}=tt{d};
for k=2:d-1
    prm=(1:phd+2);
    prm(phd+1)=phd+2;
    prm(phd+2)=phd+1;
    tt2{k}=permute(tt{d+1-k},prm);
end
tt2{d}=tt{1};
return
end