Description of tt_ranks
Home > tt2 > core > tt_ranks.m
tt_ranks
PURPOSE
Compute all ranks of the TT-decomposition in TT1.0 format
SYNOPSIS
function [rks]=tt_ranks(tt)
DESCRIPTION
Compute all ranks of the TT-decomposition in TT1.0 format
   [RKS]=TT_RANKS(TT) Computes all ranks of TT decomposition in TT1.0
   format. Please avoid its usage: it will be removed in
   future releases. Use rank() from the object-oriented version.
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
size Mode sizes of the TT-matrix
size Mode sizes of the TT-tensor
This function is called by:
tt_tensor TT-tensor constructor
tt_minres_selfprec Computation of the approximate TT-matrix inverse using self-prec method
tt_Fd_mtx Generates finite-difference diffusion matrix in QTT
tt_Fd_mtx2 TT-representation of the diffusion matrix
tt_gmres TT-GMRES method
SOURCE CODE
function [rks]=tt_ranks(tt)
%Compute all ranks of the TT-decomposition in TT1.0 format
%   [RKS]=TT_RANKS(TT) Computes all ranks of TT decomposition in TT1.0
%   format. Please avoid its usage: it will be removed in
%   future releases. Use rank() from the object-oriented version.
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
d=size(tt,1);
if (d == 1)
  rks=[];
  return
end
rks=zeros(d-1,1);
rks(1)=size(tt{1},2);
for i=2:d-2
  rks(i) = size(tt{i},3);
end
rks(d-1)=size(tt{d},2);
return
end