Description of tt_scal
Home > tt2 > core > tt_scal.m
tt_scal
PURPOSE
Multiply tensor by a scalar in TT1.0 format
SYNOPSIS
function [res] = tt_scal(tt,alpha)
DESCRIPTION
Multiply tensor by a scalar in TT1.0 format
   [RES]=TT_SCAL(TT,ALPHA) Multiply TT tensor by a scalar ALPHA in TT1.0
   format. Please avoid its usage: it will be removed in
   future releases. Use * operator from the object-oriented version
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
tt_axpy Returns A*X+P*Y in the TT-format.
tt_dist3 Accurate distance between two tensors in TT1.0 format
tt_minres_selfprec Computation of the approximate TT-matrix inverse using self-prec method
tt_Fd_mtx1 Generates finite-difference 1D matrix of \nabla(tt_a \nabla) in QTTM format.
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
SOURCE CODE
function [res] = tt_scal(tt,alpha)
%Multiply tensor by a scalar in TT1.0 format
%   [RES]=TT_SCAL(TT,ALPHA) Multiply TT tensor by a scalar ALPHA in TT1.0
%   format. Please avoid its usage: it will be removed in
%   future releases. Use * operator from the object-oriented version
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please
%ivan.oseledets@gmail.com
%---------------------------
res=tt;
res{1}=res{1}*alpha;
end