function [tt]=tt_qtoepl(x)

% returns the multilevel Toeplitz matrix tt generated by the multi-dimensional input vector x 
% in the QTT format
%
% If the size of the input vector is 2^(d_1 + 1) x ... x 2^(d_D + 1),
% then the size of the output matrix is square of order 2^(d_1) x ... x 2^(d_D).
% The first component of x is not used.
%
% April 20, 2011
% Vladimir Kazeev
% vladimir.kazeev@gmail.com
% INM RAS
% Moscow, Russia
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% For details please see the preprint
% http://www.mis.mpg.de/publications/preprints/2011/prepr2011-36.html
% Vladimir A. Kazeev, Boris N. Khoromskij and Eugene E. Tyrtyshnikov
% Multilevel Toeplitz matrices generated by QTT tensor-structured vectors and convolution with logarithmic complexity
% January 12, 2012
% Vladimir Kazeev,
% Seminar for Applied Mathematics, ETH Zurich
% vladimir.kazeev@sam.math.ethz.ch
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

d=size(x,1)-1;
tt=tt_qshiftstack(d);
tt=tt_qreshape(tt,3,[4*ones(d,1),2*ones(d,1);1,2]);
tt=tt_mv(tt,x);
tt=tt_qreshape(tt,1,[2*ones(d,2);1,1]);

tt1=cell(d,1);
for k=1:d-1
	tt1{k}=tt{k};
end;
p=size(tt{d},3);
q=size(tt{d},4);
tt1{d}=reshape(reshape(tt{d},[2*2*p,q])*reshape(tt{d+1},[q,1]),[2,2,p]);
tt=tt1;

return
end
