Description of erank
Home > tt2 > @tt_tensor > erank.m
erank
PURPOSE
Effective rank of the TT-tensor
SYNOPSIS
function [er]=erank(tt)
DESCRIPTION
Effective rank of the TT-tensor
   [ER]=ERANK(TT)
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
dot Dot product of two QTT-Tuckers
dot Frobenius dot product of two TT-matrices
dot Dot product of two TT tensors
This function is called by:
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
test_steps2 Crank-Nicolson scheme with local time-stepping
SOURCE CODE
function [er]=erank(tt)
%Effective rank of the TT-tensor
%   [ER]=ERANK(TT)
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
n=tt.n; d=tt.d; r=tt.r;
sz=dot(n.*r(1:d),r(2:d+1));
er=sz./sum(n); er=sqrt(er);
return
end