Description of ndims
Home > tt2 > @tt_tensor > ndims.m
ndims
PURPOSE
Number of dimensions of a tensor
SYNOPSIS
function d = ndims(tt)
DESCRIPTION
Number of dimensions of a tensor
   [d]=NDIMS(TT)
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
disp Command window display of a QTT_TUCKER
mvk2 Two-sided DMRG fast matrix-by-vector product
tt_exp2 Computation of the matrix exponential of a matrix in TT format
tt_minres_selfprec2 Computation of the approximate TT-matrix inverse using self-prec method
test_cross Simple function to test the cross method
SOURCE CODE
function d = ndims(tt)
%Number of dimensions of a tensor
%   [d]=NDIMS(TT)
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
d=tt.d;
return
end