Description of qr
Home > tt2 > @tt_tensor > qr.m
qr
PURPOSE
Left and right orthogonalization of the TT-format
SYNOPSIS
function [tt,rm]=qr(tt,op)
DESCRIPTION
Left and right orthogonalization of the TT-format
   [TT,RM]=QR(TT,OP) Implements the TT-QR algorithm for the
   orthogonalization of the TT-representation. OP can be 'LR'
   (for the left-right orthogonalization) and 'RL' for the
   right-left orthogonalization. Also returns R matrix for the block case,
   when r(d) or r(1) are not equal to 1.
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
size Mode sizes of the TT-matrix
qr Left and right orthogonalization of the TT-format
reshape Reshape of the TT-tensor
size Mode sizes of the TT-tensor
This function is called by:
norm Frobenius norm of the QTT-Tucker
qtt_tucker QTT-Tucker contructor (TT-format for the core+QTT-format for the factors)
round Approximate QTT-Tucker with another one with specified accuracy
axpx Matrix-by-vector multiplication with projection onto the tangent space
mvk DMRG fast matrix-by-vector product, Method 1 (less accurate)
mvk2 Two-sided DMRG fast matrix-by-vector product
dot Dot product of two TT tensors
funcrs Cross approximation of a function of a TT-tensor, Method 1
norm Frobenius norm of the TT-tensor
qr Left and right orthogonalization of the TT-format
round Approximate TT-tensor with another one with specified accuracy
sv Computes singular values of all unfoldings of a TT-tensor
move_tt_block Performs a bubble movement of a block inside a train
mvrk Computes matvec in the QTT-Tucker "rake" format
qtt_tucker_m Compute the QTT-Tucker representation of TT
qtttucker_to_linqtt Compute the standard QTT-representation from the QTT-Tucker
reort Golub-Kahan reorthogonalization
tt_als Several ALS sweeps for the approximation in the TT-format
tt_compr2 Tensor rounding in TT1.0 format
tt_dist3 Accurate distance between two tensors in TT1.0 format
tt_max_abs Compute the (supposedly) maximal in modulus element in a TT-tensor
tt_mvk2 Matrix-by-vector product by DMRG/Krylov method
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
tt_reshape Reshape of the TT-tensor
tt_tuck Computes Tucker factors and Tucker core of the TT-tensor
tt_wround Approximates a vector in the weighted norm using DMRG iterations
dmrg_cross DMRG-cross method for the approximation of TT-tensors
tt_crossl One left-to-right sweep of the TT-cross method.
tt_crossr One right-to-left sweep of the TT-cross method.
tt_rc [Y]=TT_RC(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
tt_canform1 Transforms a TT-tensor into the skeleton form
axpx [y]=AXPX(A,X)
linqtt_to_qtttucker function [qtu] = linqtt_to_qtttucker(tt, dims, eps)
als_solve_rx Computes an approximate low-rank solution for 2D case
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
SOURCE CODE
function [tt,rm]=qr(tt,op)
%Left and right orthogonalization of the TT-format
%   [TT,RM]=QR(TT,OP) Implements the TT-QR algorithm for the
%   orthogonalization of the TT-representation. OP can be 'LR'
%   (for the left-right orthogonalization) and 'RL' for the
%   right-left orthogonalization. Also returns R matrix for the block case,
%   when r(d) or r(1) are not equal to 1.
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
d=tt.d;
r=tt.r;
cr=tt.core;
ps=tt.ps;
n=tt.n;
if (strcmp(op,'lr') || strcmp(op,'LR'))
  %Orthogonalization from left-to-tight
  core0=cr(ps(1):ps(2)-1);
  pos1=1;
  for i=1:d-1
   core0=reshape(core0,[r(i)*n(i),r(i+1)]);
   [core0,ru]=qr(core0,0); %nrm(i+1)=norm(ru,'fro');
   %ru=ru;%./nrm(i+1);
   core1=cr(ps(i+1):ps(i+2)-1);
   core1=reshape(core1,[r(i+1),n(i+1)*r(i+2)]);
   core1=ru*core1;
   r(i+1)=size(core0,2);
   cr(pos1:pos1-1+r(i)*n(i)*r(i+1))=core0(:);
   cr(pos1+r(i)*n(i)*r(i+1):pos1+r(i)*n(i)*r(i+1)+r(i+1)*n(i+1)*r(i+2)-1)=core1(:);
   core0=core1;
   pos1=pos1+r(i)*n(i)*r(i+1);
  end
  %pos1 points to the d-th core
  core0=cr(pos1:pos1-1+r(d)*n(d)*r(d+1));
  core0=reshape(core0,[r(d)*n(d),r(d+1)]);
  [core0,rm]=qr(core0,0);
  r(d+1)=size(core0,2);
  cr(pos1:pos1+r(d)*n(d)*r(d+1)-1)=core0(:);
 pos1=pos1+r(d)*n(d)*r(d+1)-1;
 cr=cr(1:pos1); %Truncate storage if required
 tt.core=cr; tt.r=r;
 tt.ps=cumsum([1;tt.n.*tt.r(1:d).*tt.r(2:d+1)]);
 return
elseif (strcmp (op,'rl') || strcmp(op,'RL'))
    %Orthogonalization from right-to-left
    rm=1;
    pos1=ps(d+1)-1;
 for i=d:-1:1
    cr1=cr(ps(i):ps(i+1)-1);
    cr1=reshape(cr1,[r(i)*n(i),r(i+1)]);
    cr1=cr1*rm;
    r(i+1)=size(cr1,2);
    cr1=reshape(cr1,[r(i),n(i)*r(i+1)]);
    cr1=cr1.'; %It seems to be needed
    [u,rm]=qr(cr1,0);
    rm=rm.';
    rnew=size(u,2);
    u=u.'; %n(i)*ry(i+1)xry(i)->ry(i)xn(i)xry(i+1)
    cr(pos1-r(i+1)*n(i)*rnew+1:pos1)=u(:);
    pos1=pos1-r(i+1)*n(i)*rnew;
 end
 pos1 = pos1+1;
% pos1=pos1+r(1)*n(1)*r(2)-1;
cr=cr(pos1:end);
ps=cumsum([1;(n).*r(1:d).*r(2:d+1)]);
tt.core=cr;
tt.r=r;
tt.ps=ps;
return
else
  error('Option is not supported (yet)');
end