Description of reshape
Home > tt2 > @tt_tensor > reshape.m
reshape
PURPOSE
Reshape of the TT-tensor
SYNOPSIS
function [tt2]=reshape(tt1,sz,eps, rl, rr)
DESCRIPTION
Reshape of the TT-tensor
   [TT1]=TT_RESHAPE(TT,SZ) reshapes TT-tensor into another with mode sizes
   SZ, accuracy 1e-14
   [TT1]=TT_RESHAPE(TT,SZ,EPS) reshapes TT-tensor into another with mode
   sizes SZ and accuracy EPS
   [TT1]=TT_RESHAPE(TT,SZ,EPS, RL) reshapes TT-tensor into another with
   mode size SZ and left tail rank RL
   [TT1]=TT_RESHAPE(TT,SZ,EPS, RL, RR) reshapes TT-tensor into another with
   mode size SZ and tail ranks RL*RR
   Reshapes TT-tensor into a new one, with dimensions specified by SZ.
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
tt_reshape Reshape of the TT-tensor
This function is called by:
dot Dot product of two QTT-Tuckers
full Converts a QTT-Tucker tensor the full tensor
mtimes C=A*B: Matrix-by-matrix, matrix-by-vector, matrix-by-number in QTT-Tucker
plus A=B+C
qtt_tucker QTT-Tucker contructor (TT-format for the core+QTT-format for the factors)
round Approximate QTT-Tucker with another one with specified accuracy
times C=A.*B
axpx Matrix-by-vector multiplication with projection onto the tangent space
core Converts TT-matrix to TT1 cell-array format
ctranspose A=B'
diag Extract the diagonal of the TT-matrix
full Transform TT-matrix to a full rectangular matrix
kron2 Kronecker product of two TT-matrices in non-standard ordering
mtimes C=A*B: Matrix-by-matrix, matrix-by-vector, matrix-by-number multiplication
mvk DMRG fast matrix-by-vector product, Method 1 (less accurate)
mvk2 Two-sided DMRG fast matrix-by-vector product
subsasgn Indexing of cores of TT-format: T{I}=B
subsref Evaluate cores of TT-matrix and fields of the TT-matrix structure
tt_matrix TT_matrix class constructor
core Converts TT-tensor TT1 to old-cell array format.
diag Constructs diagonal TT-matrix from TT-tensor
dot Dot product of two TT tensors
dot2 Computes the scalar product of tt1 and tt2 as a product of numbers
full Converts TT-tensor to the full tensor
funcrs Cross approximation of a function of a TT-tensor, Method 1
funcrs2 Cross approximation of a function of a TT-tensor, Method 2
horzcat C=[A,B]
kron2 Computes the Pseudokronecker product of TT tensors:
mtimes C = A*B
norm Frobenius norm of the TT-tensor
plus A=B+C
qr Left and right orthogonalization of the TT-format
round Approximate TT-tensor with another one with specified accuracy
row Returns the k-the row of a TT-tensor
subsref Evaluate elements, cores of TT-formats and fields of the TT-structure
sv Computes singular values of all unfoldings of a TT-tensor
times A=B.*C
tt_tensor TT-tensor constructor
ttm Tensor by matrix multiplication over a given mode
vertcat C=[A;B]
move_tt_block Performs a bubble movement of a block inside a train
mvrk Computes matvec in the QTT-Tucker "rake" format
qtt_tucker_m Compute the QTT-Tucker representation of TT
qtttucker_to_linqtt Compute the standard QTT-representation from the QTT-Tucker
ten_conv Tensor-by-matrix multiplication of three-dimensional tensor
tt_als Several ALS sweeps for the approximation in the TT-format
tt_compr2 Tensor rounding in TT1.0 format
tt_dist3 Accurate distance between two tensors in TT1.0 format
tt_dot Scalar product of two TT-tensors in the TT1.0 format
tt_dot2 Logarithm of the scalar product of two tensor (to avoid overflow)
tt_mat_full_vec Multiplication of the TT-matrix by full vector in TT1.0 format
tt_mat_to_vec Flattens TT-matrix into TT-vector in the TT1.0 format
tt_max Compute the (supposedly) maximal in modulus element in a TT-tensor
tt_maxrank Maximal rank of the TT-tensor(?)
tt_mkron Compute Kronecker product of many TT-tensors.
tt_mm Matrix-by-matrix product in TT1.0 format
tt_mv Matrix-by-vector product in the TT1.0 format
tt_mvdot Fast computation of the bilinear form (Ax,y) in the TT-format
tt_mvk2 Matrix-by-vector product by DMRG/Krylov method
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
tt_qfromfull Approximates a full-format s-dimensional 2^{d} x...x 2^{d}-tensor
tt_qreshape Reshapes the cores of the input (Q)TT representation.
tt_qshiftstack returns a stack S of non-periodic shift matrices
tt_qshiftstack_p returns a stack P of periodic shift matrices
tt_qshiftstack_q returns a stack Q of non-periodic shift matrices
tt_qshiftstack_r returns a stack R of non-periodic shift matrices
tt_qtoepl returns the multilevel Toeplitz matrix tt generated by the multi-dimensional input vector x
tt_qtofull Returns a tensor _full_, given in a QTT decomposition _tt_,
tt_reshape Reshape of the TT-tensor
tt_squeeze Removes singleton dimensions from the TT-tensor
tt_tuck Computes Tucker factors and Tucker core of the TT-tensor
tt_vec_to_mat Converts TT-vector to TT-matrix in TT1.0 format
tt_wround Approximates a vector in the weighted norm using DMRG iterations
tucker_to_tt Build TT-tensor from the QTT-Tucker representation
dmrg_cross DMRG-cross method for the approximation of TT-tensors
tt_crossl One left-to-right sweep of the TT-cross method.
tt_crossr One right-to-left sweep of the TT-cross method.
tt_rc [Y]=TT_RC(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
tt_rc2 [Y]=TT_RC2(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
filters_wtt Computes the WTT transform filters for a given tensor
iwtt Inverse WTT transform with previously computed filters
tt_canform1 Transforms a TT-tensor into the skeleton form
tt_mmk2 DMRG/Krylov matrix-by-matrix multiplication
tt_smv function [res]=tt_smv(sttm, vec)
tt_sparse_for_mv Sparsify the TT matrix in TT1.0 matrix format
wtt Inverse WTT transform with previously computed filters
axpx [y]=AXPX(A,X)
lars The dimension is p^2 (thus w
linqtt_to_qtttucker function [qtu] = linqtt_to_qtttucker(tt, dims, eps)
qtttucker_to_tt function [tt]=qtttucker_to_tt(fc, cr)
tt_Fd_mtx Generates finite-difference diffusion matrix in QTT
als_prec Computes an approximate rank-1 solution to the linear system
als_solve Computes an approximate rank-1 solution to the linear system
als_solve_rx Computes an approximate low-rank solution for 2D case
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
lars The dimension is p^2 (thus w
test_dmrg_cross Simple script to test the stabilized dmrg-cross method
SOURCE CODE
function [tt2]=reshape(tt1,sz,eps, rl, rr)
%Reshape of the TT-tensor
%   [TT1]=TT_RESHAPE(TT,SZ) reshapes TT-tensor into another with mode sizes
%   SZ, accuracy 1e-14
%
%   [TT1]=TT_RESHAPE(TT,SZ,EPS) reshapes TT-tensor into another with mode
%   sizes SZ and accuracy EPS
%
%   [TT1]=TT_RESHAPE(TT,SZ,EPS, RL) reshapes TT-tensor into another with
%   mode size SZ and left tail rank RL
%
%   [TT1]=TT_RESHAPE(TT,SZ,EPS, RL, RR) reshapes TT-tensor into another with
%   mode size SZ and tail ranks RL*RR
%   Reshapes TT-tensor into a new one, with dimensions specified by SZ.
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
if (nargin == 5)
    tt2=tt_reshape(tt1,sz,eps,rl,rr);
elseif (nargin == 4)
    tt2=tt_reshape(tt1,sz,eps,rl);
else
   tt2=tt_reshape(tt1,sz,eps);
end