Description of diag
Home > tt2 > @qtt_tucker > diag.m
diag
PURPOSE
Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
SYNOPSIS
function [qt]=diag(qt)
DESCRIPTION
Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
   [QT]=DIAG(QT) Either makes a diagonal matrix from a vector in
   QTT_TUCKER, or extracts a diagonal vector from a matrix
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
diag Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
diag Extract the diagonal of the TT-matrix
diag Constructs diagonal TT-matrix from TT-tensor
This function is called by:
diag Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
qtt_tucker QTT-Tucker contructor (TT-format for the core+QTT-format for the factors)
round Approximate QTT-Tucker with another one with specified accuracy
mvk DMRG fast matrix-by-vector product, Method 1 (less accurate)
mvk2 Two-sided DMRG fast matrix-by-vector product
norm Matrix norm of the TT-matrix
diag Constructs diagonal TT-matrix from TT-tensor
funcrs Cross approximation of a function of a TT-tensor, Method 1
funcrs2 Cross approximation of a function of a TT-tensor, Method 2
round Approximate TT-tensor with another one with specified accuracy
sv Computes singular values of all unfoldings of a TT-tensor
tt_tensor TT-tensor constructor
move_tt_block Performs a bubble movement of a block inside a train
mvrk Computes matvec in the QTT-Tucker "rake" format
qtt_tucker_m Compute the QTT-Tucker representation of TT
tt_compr2 Tensor rounding in TT1.0 format
tt_mvk2 Matrix-by-vector product by DMRG/Krylov method
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
tt_reshape Reshape of the TT-tensor
tt_tuck Computes Tucker factors and Tucker core of the TT-tensor
tt_wround Approximates a vector in the weighted norm using DMRG iterations
dmrg_cross DMRG-cross method for the approximation of TT-tensors
tt_rc [Y]=TT_RC(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
Fd_mtx Finite difference approximation of scalar diffusion equation in QTT
filters_wtt Computes the WTT transform filters for a given tensor
lobpcg LOBPCG solves Hermitian partial eigenproblems using preconditioning
tt_Fd_mtx1 Generates finite-difference 1D matrix of \nabla(tt_a \nabla) in QTTM format.
tt_Fd_mtx2 TT-representation of the diffusion matrix
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
tt_gmres TT-GMRES method
test_full_KN2 The test script for the Crank-Nicolson scheme with global time stepping
SOURCE CODE
function [qt]=diag(qt)
%Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
%   [QT]=DIAG(QT) Either makes a diagonal matrix from a vector in
%   QTT_TUCKER, or extracts a diagonal vector from a matrix
%
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
d = qt.dphys;
for i=1:d
    qt.tuck{i} = diag(qt.tuck{i});
end;
end