Description of disp
Home > tt2 > @qtt_tucker > disp.m
disp
PURPOSE
Command window display of a QTT_TUCKER
SYNOPSIS
function disp(tt,name,varargin)
DESCRIPTION
Command window display of a QTT_TUCKER
CROSS-REFERENCE INFORMATION
This function calls:
rank Computes ranks of the QTT-Tucker tensor
ndims Number of dimensions of a TT-matrix
rank All or individual TT-ranks of a TT-matrix
size Mode sizes of the TT-matrix
ndims Number of dimensions of a tensor
rank Returns TT-ranks of the given tensor in TT-format
size Mode sizes of the TT-tensor
This function is called by:
display Command window display of a QTT-Tucker
display Command window display of a TT_MATRIX.
display Command window display of a TT_tensor.
test_qlaplacex_dd test code for tt_qlaplacex_dd()
test_qlaplacex_dn test code for tt_qlaplacex_dn()
test_qlaplacez_dd test code for tt_qlaplacez_dd()
test_qlaplacez_dn test code for tt_qlaplacez_dn()
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
SOURCE CODE
function disp(tt,name,varargin)
%Command window display of a QTT_TUCKER
%
disp_mode_sizes=false;
for i=1:2:length(varargin)-1
    switch lower(varargin{i})
        case 'modes'
            disp_mode_sizes=varargin{i+1};
        otherwise
            error('Unrecognized option: %s\n',varargin{i});
    end
end
if ~exist('name','var')
    name = 'ans';
end
fprintf('%s is a QTT-tucker tensor: \n',name);
fprintf('Tucker ranks: \n');
sz=size(tt.core);
rk=rank(tt.core);
for i=1:tt.dphys-1
   fprintf('%d-',sz(i));
end
fprintf('%d\n',sz(tt.dphys));
fprintf('TT-ranks for the core: \n');
for i=1:tt.dphys
   fprintf('%d-',rk(i));
end
fprintf('%d\n',rk(tt.dphys+1));
tk=tt.tuck;
fprintf('TT-ranks/mode sizes for the factors: \n');
for i=1:tt.dphys
   di=ndims(tk{i});
   ri=rank(tk{i});
   ni=size(tk{i});
   fprintf('Factor %d: ',i);
   for j=1:di
      fprintf('%d-',ri(j));
   end
   fprintf('%d\n',ri(di+1));
   if ( disp_mode_sizes )
     fprintf('Modes   : ');
     for j=1:di-1
       fprintf('%d-',ni(j));
     end
     fprintf('%d\n',ni(di));
   end
end
% %fprintf('r(1)=%d \n', r(1));
% for i=1:d
%    fprintf('r(%d)=%d \t n(%d)=%d \n',i,r(i),i,n(i));
% end
% fprintf('r(%d)=%d \n',d+1,r(d+1));