Description of full
Home > tt2 > @qtt_tucker > full.m
full
PURPOSE
Converts a QTT-Tucker tensor the full tensor
SYNOPSIS
function [a] = full(tt, sizes)
DESCRIPTION
Converts a QTT-Tucker tensor the full tensor
   [A]=FULL(QTT_TUCKER,SIZES) Converts QTT_Tucker tensor into a tensor
   with mode sizes SIZES. The dimensions should be consistent.
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
full Converts a QTT-Tucker tensor the full tensor
rank Computes ranks of the QTT-Tucker tensor
full Transform TT-matrix to a full rectangular matrix
rank All or individual TT-ranks of a TT-matrix
size Mode sizes of the TT-matrix
full Converts TT-tensor to the full tensor
rank Returns TT-ranks of the given tensor in TT-format
reshape Reshape of the TT-tensor
size Mode sizes of the TT-tensor
This function is called by:
full Converts a QTT-Tucker tensor the full tensor
full Transform TT-matrix to a full rectangular matrix
tt_qfromfull Approximates a full-format s-dimensional 2^{d} x...x 2^{d}-tensor
tt_qtofull Returns a tensor _full_, given in a QTT decomposition _tt_,
lobpcg LOBPCG solves Hermitian partial eigenproblems using preconditioning
test_qlaplace_dd test code for tt_qlaplace_dd()
test_qlaplace_dn test code for tt_qlaplace_dn()
test_qlaplacex_dd test code for tt_qlaplacex_dd()
test_qlaplacex_dn test code for tt_qlaplacex_dn()
test_qlaplacez_dd test code for tt_qlaplacez_dd()
test_qlaplacez_dn test code for tt_qlaplacez_dn()
tt_hess Numerical Hessian in a given point
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
test_steps2 Crank-Nicolson scheme with local time-stepping
SOURCE CODE
function [a] = full(tt, sizes)
%Converts a QTT-Tucker tensor the full tensor
%   [A]=FULL(QTT_TUCKER,SIZES) Converts QTT_Tucker tensor into a tensor
%   with mode sizes SIZES. The dimensions should be consistent.
%
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
a=full(tt.core);
fac=cell(tt.dphys,1);
for i=1:tt.dphys
   ti=tt.tuck{i}; ri=rank(ti,ti.d+1);
    ti=full(ti);
   fac{i}=reshape(ti,[numel(ti)/ri,ri]);
end
%And now convert tucker representation to the full one
n=size(tt.core);
for i=1:tt.dphys
   a=reshape(a,[n(i),numel(a)/n(i)]);
   a=(fac{i}*a).'; %r1r2r3 -> n1r2r3 ->r2r3n1
end
if (nargin > 1 && ~isempty(sizes))
   a=reshape(a,sizes);
end
return;