Description of round
Home > tt2 > @qtt_tucker > round.m
round
PURPOSE
Approximate QTT-Tucker with another one with specified accuracy
SYNOPSIS
function [tt]=round(tt,varargin)
DESCRIPTION
Approximate QTT-Tucker with another one with specified accuracy
   [QTT]=ROUND(QTT,EPS) Approximate QTT-Tucker tensor with relative
   accuracy EPS
   [QTT]=ROUND(QTT,EPS,RMAX) Approximate QTT-Tucker tensor with relative
   accuracy
   EPS and maximal rank RMAX. RMAX can be array of ranks or a number
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
diag Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
norm Frobenius norm of the QTT-Tucker
rank Computes ranks of the QTT-Tucker tensor
round Approximate QTT-Tucker with another one with specified accuracy
core Converts TT-matrix to TT1 cell-array format
diag Extract the diagonal of the TT-matrix
norm Matrix norm of the TT-matrix
rank All or individual TT-ranks of a TT-matrix
round Approximate TT-matrix with another one with specified accuracy
size Mode sizes of the TT-matrix
tt_matrix TT_matrix class constructor
core Converts TT-tensor TT1 to old-cell array format.
diag Constructs diagonal TT-matrix from TT-tensor
norm Frobenius norm of the TT-tensor
qr Left and right orthogonalization of the TT-format
rank Returns TT-ranks of the given tensor in TT-format
reshape Reshape of the TT-tensor
round Approximate TT-tensor with another one with specified accuracy
size Mode sizes of the TT-tensor
tt_tensor TT-tensor constructor
my_chop2 Truncation by absolution precision in Frobenius norm
ten_conv Tensor-by-matrix multiplication of three-dimensional tensor
This function is called by:
round Approximate QTT-Tucker with another one with specified accuracy
mvk2 Two-sided DMRG fast matrix-by-vector product
norm Matrix norm of the TT-matrix
round Approximate TT-matrix with another one with specified accuracy
tt_matrix TT_matrix class constructor
tt_wround Approximates a vector in the weighted norm using DMRG iterations
dmrg_cross DMRG-cross method for the approximation of TT-tensors
canm_to_qtt Converts a canonical representation to QTT-format
lobpcg LOBPCG solves Hermitian partial eigenproblems using preconditioning
tt_exp2 Computation of the matrix exponential of a matrix in TT format
tt_minres_selfprec2 Computation of the approximate TT-matrix inverse using self-prec method
tt_Fd_mtx Generates finite-difference diffusion matrix in QTT
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
test_cross Simple function to test the cross method
test_cross2 Simple function to test the cross method
test_full_KN2 The test script for the Crank-Nicolson scheme with global time stepping
test_steps2 Crank-Nicolson scheme with local time-stepping
SOURCE CODE
function [tt]=round(tt,varargin)
%Approximate QTT-Tucker with another one with specified accuracy
%   [QTT]=ROUND(QTT,EPS) Approximate QTT-Tucker tensor with relative
%   accuracy EPS
%
%   [QTT]=ROUND(QTT,EPS,RMAX) Approximate QTT-Tucker tensor with relative
%   accuracy
%   EPS and maximal rank RMAX. RMAX can be array of ranks or a number
%
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
d=tt.dphys;
core=tt.core;
tuck=tt.tuck;
eps=varargin{1};
rmax = [];
if (nargin==3)
    rmax = varargin{2};
end;
ismatrix = 0;
if (isa(tuck{1}, 'tt_matrix'))
    ismatrix = 1;
    curn = cell(d,1);
    curm = cell(d,1);
end;
for i=1:d
    if (ismatrix)
        curn{i} = tuck{i}.n;
        curm{i} = tuck{i}.m;
        tuck{i} = tt_tensor(tuck{i});
    end;
   [tuck{i},rm]=qr(tuck{i},'lr');
   core{i}=ten_conv(core{i},2,rm.');
end
if (isempty(rmax))
    core=round(core,eps);
else
    core=round(core,eps,rmax);
end;
%Round the core --- we know the result comes
%with rl orthogonality? -< No, we don't
[core, nrm] = qr(core, 'lr');
core{d} = core{d}*nrm;
rtt=rank(core);
n=size(core);
for i=d:-1:1
   cr=reshape(core{i},[rtt(i),n(i),rtt(i+1)]);
   cr=permute(cr,[2,1,3]); cr=reshape(cr,n(i),rtt(i)*rtt(i+1));
   [u,s,v]=svd(cr,'econ');
   s=diag(s);
   r=my_chop2(s,norm(s)*eps);
   u=u(:,1:r); s=s(1:r); v=v(:,1:r);
   tuck{i}=tuck{i}*(u*diag(s));
   if (isempty(rmax))
       tuck{i}=round(tuck{i},eps/sqrt(d));
   else
       tuck{i}=round(tuck{i},eps/sqrt(d), rmax);
   end;
   [tuck{i},rm]=qr(tuck{i},'lr');
   cr=rm*v';
   cr=reshape(cr,[r,rtt(i),rtt(i+1)]);
   % Shift QR to the next core block
   if (i>1)
       cr=permute(cr,[1,3,2]);
       cr = reshape(cr, r*rtt(i+1), rtt(i));
       [cr, rv] = qr(cr, 0);
       cr2 = core{i-1};
       rtuck2 = size(cr2, 2);
       cr2 = reshape(cr2, rtt(i-1)*rtuck2, rtt(i));
       cr2 = cr2*(rv.');
       rtt(i) = size(cr, 2);
       core{i-1} = reshape(cr2, rtt(i-1), rtuck2, rtt(i));
       core{i} = reshape(cr.', rtt(i), r, rtt(i+1));
   else
       core{i}=permute(cr,[2,1,3]);
   end;
end
if (ismatrix)
    for i=1:d
        tuck{i} = tt_matrix(tuck{i}, curn{i}, curm{i});
    end;
end;
tt.core=core;
tt.tuck=tuck;
return
end