Description of conj
Home > tt2 > @tt_matrix > conj.m
conj
PURPOSE
Complex conjugate of a TT-matrix
SYNOPSIS
function [b]=conj(a)
DESCRIPTION
Complex conjugate of a TT-matrix
   [B]=CONJ(A) Complex conjugate of a tt_matrix A
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
conj Complex conjugate of a TT-matrix
conj Compute a complex conjugate of TT-tensor
This function is called by:
axpx Matrix-by-vector multiplication with projection onto the tangent space
conj Complex conjugate of a TT-matrix
ctranspose A=B'
mvk DMRG fast matrix-by-vector product, Method 1 (less accurate)
mvk2 Two-sided DMRG fast matrix-by-vector product
conj Compute a complex conjugate of TT-tensor
dot Dot product of two TT tensors
funcrs Cross approximation of a function of a TT-tensor, Method 1
funcrs2 Cross approximation of a function of a TT-tensor, Method 2
mvrk Computes matvec in the QTT-Tucker "rake" format
tt_compr2 Tensor rounding in TT1.0 format
tt_mvk2 Matrix-by-vector product by DMRG/Krylov method
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
tt_wround Approximates a vector in the weighted norm using DMRG iterations
lobpcg LOBPCG solves Hermitian partial eigenproblems using preconditioning
tt_minres_selfprec2 Computation of the approximate TT-matrix inverse using self-prec method
axpx [y]=AXPX(A,X)
als_solve_rx Computes an approximate low-rank solution for 2D case
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
SOURCE CODE
function [b]=conj(a)
%Complex conjugate of a TT-matrix
%   [B]=CONJ(A) Complex conjugate of a tt_matrix A
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
b=a;
b.tt=conj(b.tt);