Description of kron
Home > tt2 > @tt_matrix > kron.m
kron
PURPOSE
Kronecker product of two TT-matrices
SYNOPSIS
function [c] = kron(a,b)
DESCRIPTION
Kronecker product of two TT-matrices
   [C]=KRON(A,B) Kronecker product of two TT-matrices. One of the
   arguments can be empty. In this case, the other, nonempty argument is
   returned
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
kron Kronecker product of two QTT_Tuckers
kron Kronecker product of two TT-matrices
tt_matrix TT_matrix class constructor
kron Kronecker product of two TT-tensors
This function is called by:
kron Kronecker product of two QTT_Tuckers
kron Kronecker product of two TT-matrices
qtttucker_to_linqtt Compute the standard QTT-representation from the QTT-Tucker
Fd_mtx Finite difference approximation of scalar diffusion equation in QTT
test_qlaplace_dd test code for tt_qlaplace_dd()
test_qlaplace_dn test code for tt_qlaplace_dn()
test_qlaplacex_dd test code for tt_qlaplacex_dd()
test_qlaplacex_dn test code for tt_qlaplacex_dn()
test_qlaplacez_dd test code for tt_qlaplacez_dd()
test_qlaplacez_dn test code for tt_qlaplacez_dn()
tt_mmk2 DMRG/Krylov matrix-by-matrix multiplication
als_solve2 A greedy method to solve a linear system
test_cross Simple function to test the cross method
test_full_KN2 The test script for the Crank-Nicolson scheme with global time stepping
test_steps2 Crank-Nicolson scheme with local time-stepping
SOURCE CODE
function [c] = kron(a,b)
%Kronecker product of two TT-matrices
%   [C]=KRON(A,B) Kronecker product of two TT-matrices. One of the
%   arguments can be empty. In this case, the other, nonempty argument is
%   returned
%
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
if (isempty(a))
  c=b;
  return;
elseif (isempty(b))
  c=a;
  return;
end
c=tt_matrix;
c.n=[(a.n);(b.n)];
c.m=[(a.m);(b.m)];
%c.d=a.d+b.d;
c.tt=kron(a.tt,b.tt);
return
end