Description of mem
Home > tt2 > @tt_matrix > mem.m
mem
PURPOSE
Computes the number of parameters in the TT-matrix
SYNOPSIS
function [mm]=mem(tt)
DESCRIPTION
Computes the number of parameters in the TT-matrix
   [MM]=MEM(TT) Computes the number of parameters in the TT-matrix, which
   is the total number of elements in the TT-cores
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
mem Computes the number of parameters in the TT-matrix
mem Computes memory for TT-tensor (only for cores)
This function is called by:
mem Computes the number of parameters in the TT-matrix
tt_save Saves TT-tensors into a Fortran-readable SDV format
tt_effrank Effective rank of the TT-tensor (correct memory definition)
tt_mem Memory required to store the tensor TT
SOURCE CODE
function [mm]=mem(tt)
%Computes the number of parameters in the TT-matrix
%   [MM]=MEM(TT) Computes the number of parameters in the TT-matrix, which
%   is the total number of elements in the TT-cores
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
mm=mem(tt.tt);
return
end