Description of norm
Home > tt2 > @tt_matrix > norm.m
norm
PURPOSE
Matrix norm of the TT-matrix
SYNOPSIS
function [nrm] = norm(t,varargin)
DESCRIPTION
Matrix norm of the TT-matrix
   The behavior is similar to the Matlab built-in function.
   NRM=NORM(TT)/NORM(TT,'fro')/NORM(TT,'F') is the Frobenius norm of the
   TT-matrix
   NRM=NORM(TT,2)/NORM(TT,'2') is the 2-norm of the TT-matrix. The 2-norm
   is approximated by a power iteration and is much more expensive than
   the Frobenius norm
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
diag Diagonal of a matrix or diagonal matrix from a vector in QTT-Tucker
dot Dot product of two QTT-Tuckers
norm Frobenius norm of the QTT-Tucker
round Approximate QTT-Tucker with another one with specified accuracy
diag Extract the diagonal of the TT-matrix
dot Frobenius dot product of two TT-matrices
norm Matrix norm of the TT-matrix
round Approximate TT-matrix with another one with specified accuracy
diag Constructs diagonal TT-matrix from TT-tensor
dot Dot product of two TT tensors
norm Frobenius norm of the TT-tensor
round Approximate TT-tensor with another one with specified accuracy
tt_tensor TT-tensor constructor
tt_random Generates a random tensor
This function is called by:
norm Frobenius norm of the QTT-Tucker
qtt_tucker QTT-Tucker contructor (TT-format for the core+QTT-format for the factors)
round Approximate QTT-Tucker with another one with specified accuracy
mvk DMRG fast matrix-by-vector product, Method 1 (less accurate)
mvk2 Two-sided DMRG fast matrix-by-vector product
norm Matrix norm of the TT-matrix
dot2 Computes the scalar product of tt1 and tt2 as a product of numbers
funcrs Cross approximation of a function of a TT-tensor, Method 1
funcrs2 Cross approximation of a function of a TT-tensor, Method 2
norm Frobenius norm of the TT-tensor
round Approximate TT-tensor with another one with specified accuracy
sv Computes singular values of all unfoldings of a TT-tensor
tt_tensor TT-tensor constructor
move_tt_block Performs a bubble movement of a block inside a train
mvrk Computes matvec in the QTT-Tucker "rake" format
qtt_tucker_m Compute the QTT-Tucker representation of TT
tt_compr2 Tensor rounding in TT1.0 format
tt_dist3 Accurate distance between two tensors in TT1.0 format
tt_dot2 Logarithm of the scalar product of two tensor (to avoid overflow)
tt_mvk2 Matrix-by-vector product by DMRG/Krylov method
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
tt_reshape Reshape of the TT-tensor
tt_tuck Computes Tucker factors and Tucker core of the TT-tensor
tt_wround Approximates a vector in the weighted norm using DMRG iterations
dmrg_cross DMRG-cross method for the approximation of TT-tensors
tt_rc [Y]=TT_RC(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
tt_rc2 [Y]=TT_RC2(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
filters_wtt Computes the WTT transform filters for a given tensor
test_qlaplace_dd test code for tt_qlaplace_dd()
test_qlaplace_dn test code for tt_qlaplace_dn()
test_qlaplacex_dd test code for tt_qlaplacex_dd()
test_qlaplacex_dn test code for tt_qlaplacex_dn()
test_qlaplacez_dd test code for tt_qlaplacez_dd()
test_qlaplacez_dn test code for tt_qlaplacez_dn()
tt_minres_selfprec Computation of the approximate TT-matrix inverse using self-prec method
tt_minres_selfprec2 Computation of the approximate TT-matrix inverse using self-prec method
als_solve2 A greedy method to solve a linear system
als_solve_rx Computes an approximate low-rank solution for 2D case
als_solve_rx_2 Computes an approximate low-rank solution for 2D case (Method 2)
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
tt_gmres TT-GMRES method
test_full_KN2 The test script for the Crank-Nicolson scheme with global time stepping
test_steps2 Crank-Nicolson scheme with local time-stepping
SOURCE CODE
function [nrm] = norm(t,varargin)
%Matrix norm of the TT-matrix
%   The behavior is similar to the Matlab built-in function.
%   NRM=NORM(TT)/NORM(TT,'fro')/NORM(TT,'F') is the Frobenius norm of the
%   TT-matrix
%
%   NRM=NORM(TT,2)/NORM(TT,'2') is the 2-norm of the TT-matrix. The 2-norm
%   is approximated by a power iteration and is much more expensive than
%   the Frobenius norm
%
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
if (nargin == 1)
  typ='F';
else
  typ=varargin{1};
end
switch typ
 case {'fro','F'} % Frobenius norm
  nrm=sqrt(abs(dot(t.tt,t.tt, true)));
 case {'2', 2} % 2-norm written by Thomas Mach
  maxit = 20; % 20 iterations
  tol = 0.01; % relative norm change
  eps1=1e-8; % tt-approximation accuracy
  rmax = 100; % maximal rank
  diag = 0; % no diagonalization
  s=1; % oversampling p=0
  for i=2:2:length(varargin)-1
    switch lower(varargin{i})
     case 'maxit'
      maxit=varargin{i+1};
     case 'tol'
      tol=lower(varargin{i+1});
     case 'x0'
      x0=varargin{i+1};
     case 'eps'
      eps1=varargin{i+1};
     case 'rmax'
      rmax=varargin{i+1};
     case 'diag'
      diag=varargin{i+1};
     case 's'
      s=varargin{i+1};
     otherwise
      error('Unrecognized option: %s\n',varargin{i});
    end
  end
  tt=t.tt;
  x = cell(s,1);
  Mx = cell(s,1);
  MU = zeros(s,s);
  if (exist('x0','var'))
    x{1}=x0;
  else
    r = tt_random(t.n,tt.d,1); % choose structured random test vectors
    x{1} = tt_tensor(r);
  end
  for j=2:s
    r = tt_random(t.n,tt.d,1); % choose structured random test vectors
    x{j} = tt_tensor(r);
  end
% orthonormalize
  for j=1:s
    for k=1:j-1
      alpha = -dot(x{k},x{j});
      x{j} = round(x{j} + alpha*x{k} ,eps1,rmax);
    end
    %norm(x{j})
    x{j} = round(x{j}/norm(x{j}) ,eps1,rmax);
  end;
  n2 = inf;
  for i=1:maxit
    for j=1:s
      if (diag)
    Mx{j}=round(t*x{j},eps1,rmax);
      end
      x{j}=round(t*x{j},eps1,rmax);
      x{j}=round(t'*x{j},eps1,rmax);
    end
% % diagonalizing
    if (diag)
      for j=1:s
    for k=1:s
      MU(j,k)=dot(x{k},Mx{j});
    end
      end
      [V,D]=eig(MU);
      [~,I]=sort(abs(diag(D)),'descend');
      V=V(:,I);
      %diag(D(I,I))
      for j=1:s
    x{j}=0*x{j};
      end
      for j=1:s
    for k=1:s
      x{k} = round(x{k}+Mx{j}*V(j,k),eps1,rmax);
    end
      end
    end
% orthonormalize
    n1=norm(x{1});
    x{1} = round(x{1}/n1,eps1,rmax);
    for j=2:s
      for k=1:j-1
    alpha = -dot(x{k},x{j});
    x{j} = round(x{j} + alpha*x{k} ,eps1,rmax);
      end
      x{j} = round(x{j}/norm(x{j}) ,eps1,rmax);
    end
    if (abs(n2-n1)/abs(n1)<tol) break; % termination by tolerance
    end
    n2=n1;
  end % Iteration
  for j=1:s
    Mx{j}=round(t*x{j},eps1,rmax);
    Mx{j}=round(t'*Mx{j},eps1,rmax);
    for k=1:s
      MU(j,k)=dot(x{k},Mx{j});
    end
  end
  nrm=sqrt(max(eig(MU))); % approx. from below to the largest singular value
  return
end