Description of rank
Home > tt2 > @tt_matrix > rank.m
rank
PURPOSE
All or individual TT-ranks of a TT-matrix
SYNOPSIS
function [r]=rank(a,varargin)
DESCRIPTION
All or individual TT-ranks of a TT-matrix
   [R]=RANK(A) Returns all (d+1) ranks of a TT-matrix A
   [R]=RANK(A,IND) Return the TT-rank with the index IND
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
rank Computes ranks of the QTT-Tucker tensor
rank All or individual TT-ranks of a TT-matrix
rank Returns TT-ranks of the given tensor in TT-format
This function is called by:
disp Command window display of a QTT_TUCKER
full Converts a QTT-Tucker tensor the full tensor
plus A=B+C
round Approximate QTT-Tucker with another one with specified accuracy
mvk2 Two-sided DMRG fast matrix-by-vector product
rank All or individual TT-ranks of a TT-matrix
tt_minres_selfprec2 Computation of the approximate TT-matrix inverse using self-prec method
SOURCE CODE
function [r]=rank(a,varargin)
%All or individual TT-ranks of a TT-matrix
%   [R]=RANK(A) Returns all (d+1) ranks of a TT-matrix A
%
%   [R]=RANK(A,IND) Return the TT-rank with the index IND
%
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
if (nargin==1)
  r=a.tt.r;
else
  i=varargin{1};
  r=rank(a.tt,i);
end
return
end