Description of size
Home > tt2 > @tt_matrix > size.m
size
PURPOSE
Mode sizes of the TT-matrix
SYNOPSIS
function [sz] = size(tt)
DESCRIPTION
Mode sizes of the TT-matrix
   [SZ]=SIZE(TT) Returns the mode sizes of the TT-matrix as a dx2 array of
   integers
 TT-Toolbox 2.2, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
disp Command window display of a QTT_TUCKER
dot Dot product of two QTT-Tuckers
full Converts a QTT-Tucker tensor the full tensor
plus A=B+C
qtt_tucker QTT-Tucker contructor (TT-format for the core+QTT-format for the factors)
round Approximate QTT-Tucker with another one with specified accuracy
axpx Matrix-by-vector multiplication with projection onto the tangent space
mtimes C=A*B: Matrix-by-matrix, matrix-by-vector, matrix-by-number multiplication
mvk DMRG fast matrix-by-vector product, Method 1 (less accurate)
mvk2 Two-sided DMRG fast matrix-by-vector product
subsasgn Indexing of cores of TT-format: T{I}=B
tt_matrix TT_matrix class constructor
dot Dot product of two TT tensors
funcrs Cross approximation of a function of a TT-tensor, Method 1
funcrs2 Cross approximation of a function of a TT-tensor, Method 2
kron Kronecker product of two TT-tensors
kron2 Computes the Pseudokronecker product of TT tensors:
mtimes C = A*B
norm Frobenius norm of the TT-tensor
numel1 Number of elements in the TT-tensors
qr Left and right orthogonalization of the TT-format
round Approximate TT-tensor with another one with specified accuracy
row Returns the k-the row of a TT-tensor
subsasgn Indexing of cores of TT-format: T{I}=B
sv Computes singular values of all unfoldings of a TT-tensor
tt_tensor TT-tensor constructor
ttm Tensor by matrix multiplication over a given mode
ind2sub2 function [sub]=ind2sub2(siz,ind)
maxvol2 Maximal volume submatrix in an tall matrix
move_tt_block Performs a bubble movement of a block inside a train
mvrk Computes matvec in the QTT-Tucker "rake" format
qtt_tucker_m Compute the QTT-Tucker representation of TT
qtttucker_to_linqtt Compute the standard QTT-representation from the QTT-Tucker
reort Golub-Kahan reorthogonalization
ten_conv Tensor-by-matrix multiplication of three-dimensional tensor
tt_add Adds two TT-tensors in TT1 format.
tt_als Several ALS sweeps for the approximation in the TT-format
tt_compr2 Tensor rounding in TT1.0 format
tt_dist3 Accurate distance between two tensors in TT1.0 format
tt_dot Scalar product of two TT-tensors in the TT1.0 format
tt_dot2 Logarithm of the scalar product of two tensor (to avoid overflow)
tt_effrank Effective rank of the TT-tensor (correct memory definition)
tt_ind2sub Correct conversion of an index to a multiindex
tt_kron7 Kronecker product of two TT-tensors in the reverse order
tt_mat_compr Tensor rounding for the TT-matrix in TT1.0 format
tt_mat_full_vec Multiplication of the TT-matrix by full vector in TT1.0 format
tt_mat_to_vec Flattens TT-matrix into TT-vector in the TT1.0 format
tt_max_abs Compute the (supposedly) maximal in modulus element in a TT-tensor
tt_maxrank Maximal rank of the TT-tensor(?)
tt_mem Memory required to store the tensor TT
tt_min_abs Computes approximation to the minimal absolute value in a TT-tensor
tt_mkron Compute Kronecker product of many TT-tensors.
tt_mm Matrix-by-matrix product in TT1.0 format
tt_mv Matrix-by-vector product in the TT1.0 format
tt_mvdot Fast computation of the bilinear form (Ax,y) in the TT-format
tt_mvk2 Matrix-by-vector product by DMRG/Krylov method
tt_mvk3 Two-sided DMRG fast matrix-by-vector product, the best version
tt_qfromfull Approximates a full-format s-dimensional 2^{d} x...x 2^{d}-tensor
tt_qltrtoepl returns the multilevel lower-triangular Toeplitz matrix tt generated by the multi-dimensional input vector x
tt_qreshape Reshapes the cores of the input (Q)TT representation.
tt_qsize For a QTT decomposition _tt_,
tt_qtoepl returns the multilevel Toeplitz matrix tt generated by the multi-dimensional input vector x
tt_qtofull Returns a tensor _full_, given in a QTT decomposition _tt_,
tt_qutrtoepl returns the multilevel upper-triangular Toeplitz matrix tt generated by the multi-dimensional input vector x
tt_rand_pos Random TT-tensor with positive elements
tt_ranks Compute all ranks of the TT-decomposition in TT1.0 format
tt_reshape Reshape of the TT-tensor
tt_reverse Returns a reversed TT representation
tt_scal2 Stabilized multiplication of a scalar by vector
tt_size Mode dimensions of a TT-tensor in TT1.0 format
tt_squeeze Removes singleton dimensions from the TT-tensor
tt_transp Transposition of the TT matrix
tt_tuck Computes Tucker factors and Tucker core of the TT-tensor
tt_vec_to_mat Converts TT-vector to TT-matrix in TT1.0 format
tt_wround Approximates a vector in the weighted norm using DMRG iterations
tucker_to_tt Build TT-tensor from the QTT-Tucker representation
dmrg_cross DMRG-cross method for the approximation of TT-tensors
tt_crossl One left-to-right sweep of the TT-cross method.
tt_crossr One right-to-left sweep of the TT-cross method.
tt_rc [Y]=TT_RC(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
tt_rc2 [Y]=TT_RC2(D,N,ARR,ELEM_FUN,EPS,[OPTIONS])
Fd_mtx Finite difference approximation of scalar diffusion equation in QTT
Fd_mtx2 Finite difference approximation of a 2D scalar diffusion equation in QTT
canm_to_qtt Converts a canonical representation to QTT-format
filters_wtt Computes the WTT transform filters for a given tensor
iwtt Inverse WTT transform with previously computed filters
lobpcg LOBPCG solves Hermitian partial eigenproblems using preconditioning
test_qlaplace_dd test code for tt_qlaplace_dd()
test_qlaplace_dn test code for tt_qlaplace_dn()
test_qlaplacex_dd test code for tt_qlaplacex_dd()
test_qlaplacex_dn test code for tt_qlaplacex_dn()
test_qlaplacez_dd test code for tt_qlaplacez_dd()
test_qlaplacez_dn test code for tt_qlaplacez_dn()
tt_canform1 Transforms a TT-tensor into the skeleton form
tt_exp2 Computation of the matrix exponential of a matrix in TT format
tt_minres_selfprec Computation of the approximate TT-matrix inverse using self-prec method
tt_mmk2 DMRG/Krylov matrix-by-matrix multiplication
tt_qlaplace_dd returns a rank-3,4...4 QTT decomposition of
tt_qlaplace_dn returns a rank-4,5...5 QTT decomposition of
tt_qlaplacex_dd returns a rank-5 QTT decomposition of
tt_qlaplacex_dn returns a rank-4 QTT decomposition of
tt_qlaplacez_dd returns a rank-10 QTT decomposition of
tt_qlaplacez_dn returns a rank-8 QTT decomposition of
tt_smv function [res]=tt_smv(sttm, vec)
tt_sparse_for_mv Sparsify the TT matrix in TT1.0 matrix format
wtt Inverse WTT transform with previously computed filters
axpx [y]=AXPX(A,X)
linqtt_to_qtttucker function [qtu] = linqtt_to_qtttucker(tt, dims, eps)
qtttucker_to_tt function [tt]=qtttucker_to_tt(fc, cr)
tt_Fd_mtx Generates finite-difference diffusion matrix in QTT
tt_Fd_mtx1 Generates finite-difference 1D matrix of \nabla(tt_a \nabla) in QTTM format.
tt_Fd_mtx2 TT-representation of the diffusion matrix
tt_hess Numerical Hessian in a given point
als_prec Computes an approximate rank-1 solution to the linear system
als_solve Computes an approximate rank-1 solution to the linear system
als_solve2 A greedy method to solve a linear system
als_solve_rx Computes an approximate low-rank solution for 2D case
als_solve_rx_2 Computes an approximate low-rank solution for 2D case (Method 2)
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
dmrg_solve2 Solution of linear systems in TT-format via DMRG iteration
tt_gmres TT-GMRES method
test_full_KN2 The test script for the Crank-Nicolson scheme with global time stepping
SOURCE CODE
function [sz] = size(tt)
%Mode sizes of the TT-matrix
%   [SZ]=SIZE(TT) Returns the mode sizes of the TT-matrix as a dx2 array of
%   integers
%
%
% TT-Toolbox 2.2, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
n=tt.n; m=tt.m;
n0=[n,m];
    sz=n0;
return
end