Description of tt_matrix
Home > tt2 > @tt_matrix > tt_matrix.m
tt_matrix
PURPOSE
TT_matrix class constructor
SYNOPSIS
function t = tt_matrix(varargin)
DESCRIPTION
TT_matrix class constructor
   [T]=TT_MATRIX(TT_MAT) - copy constructor
   [T]=TT_MATRIX(TT,N,M) - construct TT-matrix from the TT-tensor. N and M
   are the row and column mode sizes. N and M can be either numbers, or
   array of numbers
   [T]=TT_MATRIX(CELL) - construct TT-matrix from TT1 format
   [T]=TT_MATRIX(FULL_ARR) - construct TT-matrix from a full
   2d-dimensional array FULL_ARR
 TT Toolbox 2.1, 2009-2012
This is TT Toolbox, written by Ivan Oseledets et al.
Institute of Numerical Mathematics, Moscow, Russia
webpage: http://spring.inm.ras.ru/osel
For all questions, bugs and suggestions please mail
ivan.oseledets@gmail.com
---------------------------
CROSS-REFERENCE INFORMATION
This function calls:
round Approximate QTT-Tucker with another one with specified accuracy
round Approximate TT-matrix with another one with specified accuracy
size Mode sizes of the TT-matrix
tt_matrix TT_matrix class constructor
reshape Reshape of the TT-tensor
round Approximate TT-tensor with another one with specified accuracy
size Mode sizes of the TT-tensor
tt_tensor TT-tensor constructor
tt_mat_to_vec Flattens TT-matrix into TT-vector in the TT1.0 format
This function is called by:
matrix Converts a vector to a matrix in the QTT-Tucker format
plus A=B+C
round Approximate QTT-Tucker with another one with specified accuracy
kron Kronecker product of two TT-matrices
kron2 Kronecker product of two TT-matrices in non-standard ordering
mtimes C=A*B: Matrix-by-matrix, matrix-by-vector, matrix-by-number multiplication
plus A=B+C
times A=B.*C
tt_matrix TT_matrix class constructor
diag Constructs diagonal TT-matrix from TT-tensor
mvrk Computes matvec in the QTT-Tucker "rake" format
tt_eye Identity matrix in the TT-format
tt_reshape Reshape of the TT-tensor
tt_shf Upper shift matrix in the QTT-format
IpaS A special bidiagonal matrix in the QTT-format
tt_exp2 Computation of the matrix exponential of a matrix in TT format
tt_minres_selfprec2 Computation of the approximate TT-matrix inverse using self-prec method
tt_qlaplace_dd returns a rank-3,4...4 QTT decomposition of
tt_qlaplace_dn returns a rank-4,5...5 QTT decomposition of
tt_qlaplacex_dd returns a rank-5 QTT decomposition of
tt_qlaplacex_dn returns a rank-4 QTT decomposition of
tt_qlaplacez_dd returns a rank-10 QTT decomposition of
tt_qlaplacez_dn returns a rank-8 QTT decomposition of
qtt_mg_interp The simplest multigrid operator in QTT as a TT-matrix
als_solve2 A greedy method to solve a linear system
dmrg_eigb Find several minimal eigenvalues of a TT-matrix using DMRG method
dmrg_rake_solve2 DMRG-type method for the solution of linear systems in QTT-Tucker format
test_full_KN2 The test script for the Crank-Nicolson scheme with global time stepping
SOURCE CODE
function t = tt_matrix(varargin)
%TT_matrix class constructor
%   [T]=TT_MATRIX(TT_MAT) - copy constructor
%
%   [T]=TT_MATRIX(TT,N,M) - construct TT-matrix from the TT-tensor. N and M
%   are the row and column mode sizes. N and M can be either numbers, or
%   array of numbers
%
%   [T]=TT_MATRIX(CELL) - construct TT-matrix from TT1 format
%
%   [T]=TT_MATRIX(FULL_ARR) - construct TT-matrix from a full
%   2d-dimensional array FULL_ARR
%
% TT Toolbox 2.1, 2009-2012
%
%This is TT Toolbox, written by Ivan Oseledets et al.
%Institute of Numerical Mathematics, Moscow, Russia
%webpage: http://spring.inm.ras.ru/osel
%
%For all questions, bugs and suggestions please mail
%ivan.oseledets@gmail.com
%---------------------------
if (nargin == 0)
    t1=tt_tensor;
    t.tt=t1;
    t.n=0; %n-dimensions
    t.m=0; %m-dimensions
    t = class(t, 'tt_matrix');
    return;
end
% Copy CONSTRUCTOR
if (nargin == 1) && isa(varargin{1}, 'tt_matrix')
    t=tt_matrix;
    t.tt = varargin{1}.tt;
    t.n = varargin{1}.n;
    t.m = varargin{1}.m;
    return;
end
% From tt_tensor
if (isa(varargin{1}, 'tt_tensor'))
    tt=varargin{1};
    d=tt.d;
    if (nargin==3)&&(isa(varargin{2},'double'))&&(isa(varargin{3},'double'))
        n=varargin{2};
        m=varargin{3};
        if ( numel(n) == 1 )
            n=n*ones(d,1);
        end
        if ( numel(m) == 1 )
            m=m*ones(d,1);
        end
    else
        % Square matrix
        n = round(sqrt(tt.n));
        m = n;
    end;
    t=tt_matrix;
    t.n=n;
    t.m=m;
    t.tt=tt;
return
end
%From old format
if (nargin == 1) && isa(varargin{1},'cell')
    t=tt_matrix;
   tt=varargin{1};
   tt1=tt_mat_to_vec(tt);
   t.tt=tt_tensor(tt1);
   d=t.tt.d;
   n=zeros(d,1);
   m=zeros(d,1);
   for i=1:d
      n(i)=size(tt{i},1);
      m(i)=size(tt{i},2);
   end
   t.n=n;
   t.m=m;
end
if (nargin == 1 && isa(varargin{1},'double') || nargin ==2 && isa(varargin{1},'double') && isa(varargin{2},'double'))
    t=tt_matrix;
    b=varargin{1};
    if ( nargin == 2 && isa(varargin{2},'double'))
      eps=varargin{2};
    else
      eps=1e-14;
      fprintf('Accuracy not specified, using %3.2e \n',eps);
    end
    nm=size(b);
    d=numel(nm);
    d=d/2;
    n=nm(1:d);
    m=nm(d+1:2*d);
    prm=1:2*d; prm=reshape(prm,[d,2]); prm=prm';
    prm=reshape(prm,[1,2*d]); %Transposed permutation
    b=permute(b,prm);
    if (numel(n.*m) == 1 )
      b=b(:);
    else
    b=reshape(b,n.*m);
    end
    tt=tt_tensor(b,eps);
    t.tt=tt;
    t.n=n';
    t.m=m';
end
if (nargin == 3 && isa(varargin{1},'tt_tensor') && isa(varargin{2},'double') && isa(varargin{3},'double'))
    t=tt_matrix;
    tt=varargin{1};
    n=varargin{2};
    m=varargin{3};
    t.tt=tt;
    t.n=n;
    t.m=m;
end
% From a simple tt_matrix struct without class definition
if (nargin == 1) && isa(varargin{1}, 'struct')
    t.tt=tt_tensor(varargin{1}.tt);
    t.n=varargin{1}.n; %n-dimensions
    t.m=varargin{1}.m; %m-dimensions
    t = class(t, 'tt_matrix');
    return;
end;
return;